### ISSUE TITLE
When try to send email multiple users i got duplicate entry issue

### ISSUE THREAD

**Issue by yubitib** [jdavidbakr/mail-tracker#10]
PDOException: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '64b22935e5897fe90a777c394c44dec1@swift.generated' for key 'sent_emails_message_id_unique'

**Comment by jdavidbakr** [comment]
Could you post your actual send command as well as your mail driver info (without credentials of course)?

**Comment by sasureshkumar** [comment]
@jdavidbakr when we add multiple emails as **to** it generates many emails with same message id hence message_id is unique in DB it throws error. I got this error with SES driver.

It works if we add multiple emails in CC / BCC.

**Comment by yubitib** [comment]
Let's me know any way to fix it? :-1:

**Comment by jdavidbakr** [comment]
Sorry, been very busy with other projects, so haven't had a chance to look at this issue.  Obviously, the swift mailer is attaching the same ID to all "to" addresses, I just need to determine the best method to overcome that.

**Comment by jdavidbakr** [comment]
If you take the unique index off of that column it shouldn't break anything.  I'll release a new version that has that removed from the migration but won't add a new migration to drop the unique index, so for previously installed deployments just go into the database and drop the unique index.
