### ISSUE TITLE
is it possible to exclude certain headers from being logged?

### ISSUE THREAD

**Issue by vesper8** [jdavidbakr/mail-tracker#100]
I started using https://usehelo.com/ and it adds a few custom headers which are enormous and it causes issues with this package and says the 'headers' are too long. Those headers are easily identifiable, is it possible to drop them before inserting the record inside the `sent_emails` table?

If not possible through the configuration, is it possible to intercept an event prior to the database insert occurring so I can strip the header there?

Thank you

**Comment by vesper8** [comment]
Well for anyone wondering I was able to do this by creating a model Observer like so:

```
<?php

namespace App\Observers;

use jdavidbakr\MailTracker\Model\SentEmail;

class SentEmailObserver
{
    public function creating(SentEmail $sentEmail)
    {
        $acceptedHeaders = [];

        $headers = explode("\r\n", $sentEmail->headers);

        for ($i=0; $i < count($headers) ; $i++) { 
            if(substr($headers[$i], 0, 6) !== 'X-HELO') {
                $acceptedHeaders[] = $headers[$i];
            }
        }

        $sentEmail->headers = implode("\r\n", $acceptedHeaders);
    }
}
```

And then in a ServiceProvider's boot method:

```
\jdavidbakr\MailTracker\Model\SentEmail::observe(App\Observers\SentEmailObserver::class);
```

This removes any header that begins with `X-HELO`

**Comment by jdavidbakr** [comment]
I think this is the most Eloquent solution.

**Comment by vesper8** [comment]
@jdavidbakr Thanks, I do feel like it would be nice to have a configurable whitelist/blacklist for headers

**Comment by jdavidbakr** [comment]
I won't probably build it but would accept a PR
