### ISSUE TITLE
Queue problems

### ISSUE THREAD

**Issue by winkelco** [jdavidbakr/mail-tracker#101]
Hello. Email tracking dont work with queues

**Comment by jdavidbakr** [comment]
Can you give more troubleshooting info?  How are you running the queue workers?  Do you have a complex queue structure?

**Comment by winkelco** [comment]
I am using laravel horizon. 
I have nothing complex. I just have a mailable

// controller
Mail::queue(new WelcomeClient($customer));

// WelcomeClient
public function build(){
        return $this->markdown('emails.create-account.welcome-client')
        ->to($this->customer->email)
        ->subject(trans('emails/welcome.subject-client'))
        ->with([
            'customer' => $this->customer
        ]);
}

**Comment by jdavidbakr** [comment]
so the mail is going out but it's not getting the tracker?  Does it work without the queue?  Did you restart horizon after installing the package?

**Comment by winkelco** [comment]
**so the mail is going out but it's not getting the tracker?**
I receive the email correctly but the tracking record is not saved in the database

**Does it work without the queue?**
Yes. without queue work perfectly

**Did you restart horizon after installing the package?**
Yes. Horizon work normally  with other jobs

**Comment by winkelco** [comment]
I managed to make it work by overwriting the event LogSendingMessage but this is not good.

**Comment by jdavidbakr** [comment]
I have multiple systems sending email via the queue and have never had this issue.  My question about Horizon is just that this sounds like the queue workers are not running a version with the plugin installed, which will happen if you deploy a new version but the queue workers don't get restarted.

**Comment by timramseyjr** [comment]
> **so the mail is going out but it's not getting the tracker?**
> I receive the email correctly but the tracking record is not saved in the database
> 
> **Does it work without the queue?**
> Yes. without queue work perfectly
> 
> **Did you restart horizon after installing the package?**
> Yes. Horizon work normally with other jobs

@winkelco - Did you ever figure this one out? I am having the exact same issues with horizon.

**Comment by jdavidbakr** [comment]
Check the `config/mail-tracker.php` and make sure `tracker-queue` matches the queue you are expecting.

**Comment by timramseyjr** [comment]
> Check the `config/mail-tracker.php` and make sure `tracker-queue` matches the queue you are expecting.

Thanks. I was using the default queue for the mail. The issue is `beforeSendPerformed` is not even being called to create the record in `sent_emails`

> I have multiple systems sending email via the queue and have never had this issue

Are you using Redis for your queue connection?

**Comment by jdavidbakr** [comment]
Yes to your question about Redis.

The `beforeSendPerformed` should be called by the swift mailer.  Can you check to make sure the `MailTrackerServiceProvider` is executing the `boot()` function?  You're not doing anything strange with the default swift mailer, are you?

**Comment by timramseyjr** [comment]
> Yes to your question about Redis.
> 
> The `beforeSendPerformed` should be called by the swift mailer. Can you check to make sure the `MailTrackerServiceProvider` is executing the `boot()` function? You're not doing anything strange with the default swift mailer, are you?

Yes, it is executing the boot. I am mailing in a Job and if I skip the queue with `CustomJob::dispatchNow()` it works, but as soon as I queue it with `CustomJob::dispatch()` it stops working.

**Comment by jdavidbakr** [comment]
So even in the queued job the `boot` function is being executed?  It really feels like there is some sort of configuration difference between your Horizon workers and your front end, there should be no difference in the way the provider works between the two.

**Comment by timramseyjr** [comment]
> So even in the queued job the `boot` function is being executed? It really feels like there is some sort of configuration difference between your Horizon workers and your front end, there should be no difference in the way the provider works between the two.

Yes, but I think you are right and my issues have something to do with my local environment, because I just checked and the production code is working. I am using homestead and mailtrap, but I am just going to move on since my issues now are just on my development box. Thanks for you help!
