### ISSUE TITLE
[Feature request] Track first open and click of an email

### ISSUE THREAD

**Issue by jcalonso** [jdavidbakr/mail-tracker#104]
Hi there!,

I have a small feature request that can improve this package.

It would be very useful when gathering statistics for email campaigns to track the first open and first click of an email, this could be easy done by adding `opened_at` and `clicked_at` in the `sent_email` table and the respective logic to update those columns only when they are empty.

Let me know what you think. :)

**Comment by jdavidbakr** [comment]
Feel free to submit a pull request

**Comment by jdavidbakr** [comment]
Added to version 5.x
