### ISSUE TITLE
Tracker not working on my mail instance

### ISSUE THREAD

**Issue by anny21** [jdavidbakr/mail-tracker#107]
I created a new mailer with new settings, like am not using settings from my env because i wanted users to set up their own personal smtp details to send mail but the tracker workers when i use the default settings in env and not the custom smtp.
Mail is sending but not being logged in sent email table.

`$host = $this->user->host;
            $username = $this->user->username;
            $port = $this->user->port;
            $encryption = 'tls';
            $password = $this->user->password;
            $transport = (new \Swift_SmtpTransport($host, $port))
                               ->setUsername($username)
                               ->setPassword($password)
                               ->setEncryption($encryption);
        //dd($transport);
            \Mail::setSwiftMailer(new \Swift_Mailer($transport));
            return \Mail::to($this->email)->send(new Mail($this->email));`

**Comment by jdavidbakr** [comment]
It looks like you're instantiating the swift SMTP transport class directly instead of using it through Laravel.  You'll have to manually register the plugin, which you should be able to see how to do if you code-dive into the service provider.
