### ISSUE TITLE
See SNS/SES meta in dashboard

### ISSUE THREAD

**Issue by fibis** [jdavidbakr/mail-tracker#109]
We have connected the mail tracker via sns with ses to see which emails are bounced. But I can't see any information about it in the mail manager dashboard. Is this right?

**Comment by jdavidbakr** [comment]
First make sure your SNS subscription is active and not pending - it should activate pretty much immediately after creating it. 
If it doesn't then your endpoint is not accessible to SNS.  If that's fine, you can troubleshoot this by subscribing your email to the notification and make sure you are getting delivery and bounce notifications.  If not, you may not have SES set up to properly send notifications.  Be sure to consult the SES documentation for the proper way this needs to be set up.
