### ISSUE TITLE
Mail tracker track all email

### ISSUE THREAD

**Issue by yubitib** [jdavidbakr/mail-tracker#11]
Hi jdavidbakr,

Mail tracker is great work, but it's track all emails, I think it should be selectable

Thanks.

**Comment by fabiopenagoli** [comment]
It's should be enough passing a parameter or call a method to exclude specific sends.

**Comment by vesper8** [comment]
I want the same thing, my application sends a lot of internal emails such as when a daily backup is performed.. and I have no need to track those emails.

Has anyone figured out an easy way to not track certain emails?

I think something like this would work. What do you guys think?

In https://github.com/jdavidbakr/mail-tracker/blob/master/src/MailTracker.php
```
    protected function createTrackers($message)
    {
        $doNotTrackList = config('mail-tracker.do-not-track');
        
        foreach($message->getTo() as $to_email=>$to_name) {
            if(in_array($to_email, $doNotTrackList)) {
                continue;
            } else {
                foreach($message->getFrom() as $from_email=>$from_name) {
                    ...
                }
            }
        }
    }
```

**Comment by NathanGeerinck** [comment]
I have the same issue but for now I have a temporary solution until the new feature is there:

You can pass on headers with your email. In this case we will pass on a header that the tracking needs to be false:
```
\Mail::send('email.test', [], function ($message) use($email, $subject, $name, $model) {
    $message->from('from@johndoe.com', 'From Name');
    $message->sender('sender@johndoe.com', 'Sender Name');
    $message->to($email, $name);
    $message->subject($subject);

    // Set over here the track variable to true/false
    $message->getHeaders()->addTextHeader('track', 'false);
});
```

Now we can see see if we want to track te email in the SentEvent (see [docs](https://github.com/jdavidbakr/mail-tracker#events)):
```
public function handle(EmailSentEvent $event)
{
    if ($event->sent_email->getHeader('campaign_id') == false) {
        $email = SentEmail::where($event->sent_email);
        $email->delete();
    }
}
```

This should be a temporary solution for your problems! :)

**Comment by jdavidbakr** [comment]
Added the ability to inject a header `X-No-Track` into the message to prevent it from being tracked (2.1.7)
