### ISSUE TITLE
Basic question 

### ISSUE THREAD

**Issue by joni051** [jdavidbakr/mail-tracker#111]
hello I have a question and I didn't know how else to solve it

during the tests with mailtrap, everything worked well, the opens and the clicks also, but from my server only the clicks work me, do you have idea that it may be happening?

thank you in advance.

**Comment by jdavidbakr** [comment]
Look at the raw email and locate the URL for the pingback (it will be a one pixel image) - see if you are able to open that URL, and if not, that should help you track down why the opens are not tracking. It also could be that your email client is blocking images for your email.
