### ISSUE TITLE
Resend bounced mails

### ISSUE THREAD

**Issue by fibis** [jdavidbakr/mail-tracker#112]
Since the SES IP addresses are sometimes on spam lists, some E-Mail Providers are bouncing our mails. Since SES is also sending from different IP addresses, it is often possible to send mails to the same email provider without getting bounced. 

We would like to resend our mails when they are getting bounced after a view hours.
1. Does this package this already?
2. If not, is there also a bounce event and not only a permanent bounced event?

**Comment by jdavidbakr** [comment]
By definition, a non-permanent bounce means that the mail server will retry at a later time.  Only after a certain time will a transient bounce turn into a permanent bounce.  You should be able to wait for the permanent bounce and resend off of that event, if you wish.
