### ISSUE TITLE
Is there no way to disable mail tracking for specific emails? such as the email verification/password reset emails?

### ISSUE THREAD

**Issue by vesper8** [jdavidbakr/mail-tracker#113]
Right now it appears that enabling this package adds mail tracking and link rewriting to every outgoing email without exception which is very much undesirable in my case. I have lots of internal emails being emitted (admin emails) and then there's also password resets and email verification etc.. I only want to track a specific set of emails.. it would be greatly appreciated if there was a way to blacklist/whitelist which emails are tracked.. is this currently possible?

**Comment by vesper8** [comment]
Ideally I would want it disabled for all emails unless specifically enabled

**Comment by jdavidbakr** [comment]
No, there is no mechanism to only add tracking data to a subset of sent emails.  I don't have any intention of changing this but would be willing to look at a PR.  Off the top of my head I don't have a great idea of how to accomplish selective tracking.

**Comment by vesper8** [comment]
I haven't tested this fully but it does appear to work

I set track-links and inject-pixel to false in the config file, then prior to sending an email which I want tracked I add this code

```
                config()->set('mail-tracker.inject-pixel', true);
                config()->set('mail-tracker.track-links', true);
```

That does the trick of only adding the above on emails I want to track. I don't know however if having them set to false will interfere with the actual tracking being logged when a user opens an email or clicks on a link. Do you have any insight as to whether this would work?

Thanks

**Comment by jdavidbakr** [comment]
That looks like it would work.  Those config values are only accessed when it's time to inject the tracking pixels.  Good idea.

**Comment by yormy** [comment]
I took a different approach on this, which works well in my case.
Actually I still want to emails to be tracked, but secure content to be removed 

1) I added a messageid to the header to know in a later stage what needs to be done with the mail.
