### ISSUE TITLE
Markdown email hash not generated for href

### ISSUE THREAD

**Issue by mukdagr8** [jdavidbakr/mail-tracker#114]
Laravel v5.8.37
mail-tracker v3.0.4

Emails generated using a normal view method in Laravel will have the href replaced with the correct hashed link and are tracked with the hashed link stored in the DB.

`$this->view('vendor.notifications.email')`

When using markdown emails the href is replaced with the base email tracking link. The hash is not generated nor is it stored in the DB. If you navigate to the link from the email it is a broken link then as it has no hash to find and redirect

`$this->markdown('emails.orders.shipped')`

**Comment by jdavidbakr** [comment]
I'm not able to reproduce this in my environment, I think I'll need to see your specific case.  The trackers are not injected until after the markdown has been converted to html, so it seems there may be an outlier condition that your email is generating that the link tracker injection code is not recognizing or is incorrectly parsing for some reason.
