### ISSUE TITLE
It does not track emails if I update credentials on runtime

### ISSUE THREAD

**Issue by arkniazi** [jdavidbakr/mail-tracker#118]
I'm trying to update credentials of email client on runtime. 
Because I'll be sending  emails from different accounts.

I'm updating the credentials in following way. 
```
$transport = new \Swift_SmtpTransport( $host, $port, $security);
$transport->setUsername($username);
$transport->setPassword($password);
$mailer->setSwiftMailer(new Swift_Mailer($transport));
```

**Comment by jdavidbakr** [comment]
You'll have to duplicate what happens in MailTrackerServiceProvider::registerSwiftPlugin() to reinstall the plugin if you reinstantiate the swift mailer.

**Comment by arkniazi** [comment]
Okay, got it. 
It's working fine now. 
`$mailer->getSwiftMailer()->registerPlugin(new MailTracker());
`
Thanks
