### ISSUE TITLE
Storing SentEmail id against model

### ISSUE THREAD

**Issue by bretto36** [jdavidbakr/mail-tracker#12]
Hi. 

Loving the package so far. I was just wondering if it's possible to get the SentEmail id after the email has been sent so i can store it against a model in my database. 

I am writing a system that sends an email reminder, and i'd like to store the mail message against the model in my database. I'm not sure if your code already has the functionality to do it or not. 

Would appreciate your input

**Comment by jdavidbakr** [comment]
Check out the Readme under "Events" - you can listen to the EmailSentEvent and do additional processing there.

**Comment by bretto36** [comment]
Hi there, so i followed the instructions in the readme. I'm unable to see the headers that i've added in the database or in the event listener. 

I'm using Laravel 5.3

I've tried your exact code, and a few variations after googling


        ```
$reminderHistory = ReminderHistory::create([
            'account_id' => $this->account->id,
            'reminder_id' => $this->reminder->id,
            'invoice_id' => $this->invoice->id,
        ]);

        Mail::to($this->invoice->debtor->email)
            ->send(new InvoiceReminder($this->account, $this->reminder, $this->invoice), [], function ($message) use ($reminderHistory) {
                // Add 2 types of headers
                $message->getSwiftMessage()->getHeaders()->addTextHeader('X-Reminder-History-ID', $reminderHistory->id);
                $message->getHeaders()->addTextHeader('X-Reminder-History-ID', $reminderHistory->id);
            });
```

Then in my listener when i output it i get null

`dd($event->sent_email->getHeader('X-Reminder-History-ID'));`

**Comment by bretto36** [comment]
Had to add the callback into the InvoiceReminder class, couldn't add it using the callback on the Mail::send class. Because i was passing a Mailable Object, not a view
