### ISSUE TITLE
Link Tracker mangles links that contain `#` hashes

### ISSUE THREAD

**Issue by ericlucit** [jdavidbakr/mail-tracker#120]
Example:

I have a link like this : `https://some.domain.com/#/some-place`

The link tracker seems to mangle the link into this : `https://the.backend.com/email/n?l=%23%2Fsome-place&h=zfKFxAjhIfmo92MhuIVGxyCsbD3ui0Le`

Then, the actual redirect ends up giving me an error `ERR_TOO_MANY_REDIRECTS` and results at this link : `https://my.backend.com/email/n?l=%23%2Fsome-place&h=zfKFxAjhIfmo92MhuIVGxyCsbD3ui0Le#/some-place`

I tried to look at the code to see any quick fix, but basically my regex knowledge is no better than a toddlers!

Any ideas? - We are linking to a single page PWA that uses React's Hash-Router - so, all routes have a `#` in them

**Comment by jdavidbakr** [comment]
I just performed a test and I'm not getting this issue.  It almost looks to me like the URL you are injecting doesn't contain the domain, i.e. just starts with the `#` part.  Can you verify that is not the case, and if not, can you post what is actually in the email before the tracker attempts to fix it?

**Comment by ericlucit** [comment]
You can close this - I apologize for the error 

It was caused by TinyMCE mangling the links prior to submission when composing the email, which I have now resolved with this : https://stackoverflow.com/a/3394937

Thanks for checking into this - This library has been a great drop-in for our application and we have been able to hook into the events, etc. very easily to customize everything.

Thanks!
