### ISSUE TITLE
Logging Content Question

### ISSUE THREAD

**Issue by devoncmather** [jdavidbakr/mail-tracker#121]
Hello,

Currently, the package is logging the original content but there have been times when trying to debug the tracked links that this becomes a bit of a pain. I would be most interested in logging the email as it was when it was sent to the recipient. Would also probably make some tests easier to write.

Is there a particular reason for opting to use original_content rather than original_content + injected tracking pixel + links?

Warm regards,
Devon Mather

**Comment by jdavidbakr** [comment]
I do think it's best to have the original email stored in its unedited form.  One of the biggest reasons is that you can view the email in the admin, and if the links and tracking pixel are in there then you're going to get false reporting if you ever look at the email in the admin or click on any of the links there.  You are welcome to extend the class in your project and store the modified content, perhaps in a separate column in the database, but that is not something I intend to include in this package.
