### ISSUE TITLE
Weird issue with tracked links

### ISSUE THREAD

**Issue by devoncmather** [jdavidbakr/mail-tracker#122]
This package has worked pretty well for us so far, so thanks for that 👍

Currently experiencing a weird issue with the subdomain where it sometimes has two `..` after it rather than one.

![Xnip2020-11-04_12-46-59](https://user-images.githubusercontent.com/62438577/98059952-8cbf2280-1e9c-11eb-948d-e0afda3f1c47.jpg)

The user in question seems to be using Windows with Outlook and Internet Explorer/Edge.

The logged emails don't show the links with two dots after subdomain. And since we are writing the record to the db it must have reached us using the subdomain with regular formatting otherwise it wouldn't have managed to connect and get a 404 page. So it seems like either the email in outlook is having the redirect url re-written, or possibly its happening in Explorer.

Has anyone has similar issues on Windows?

I have tried testing this on a friends computer with outlook and windows as well as using browser stack with the trackign links both worked ok 🤷‍♂️

**Comment by jdavidbakr** [comment]
Can you look in your server logs and see the requests that came in for both of the links?

**Comment by devoncmather** [comment]
Hi thanks for the reply, we bcc an internal email address to a cloud outlook address, that one shows links correctly. 

So the only thing I can think here is, outlook on windows seems to be causing some sort of url mismatch?

I have turned off url tracking for now, as it's too critical for the business to have email links not working. I understand this is quite tricky to debug, so just registering this here in case others end up having similiar issues.

**Comment by jdavidbakr** [comment]
Closing pending further troubleshooting information.
