### ISSUE TITLE
Add Opened At datetime column to sent_emails table

### ISSUE THREAD

**Issue by bretto36** [jdavidbakr/mail-tracker#13]
Any chance we could add an opened_at column so we can see when they first opened the email

Or possibly a separate table to track each time they opened the email maybe

**Comment by fabiopenagoli** [comment]
I agree, it would be useful having the date of opening.
It should be enough to have the corresponding event.

**Comment by bretto36** [comment]
For anyone interested I did this using the event @fabiopenagoli mentioned

I created a database migration 

```
Schema::table('sent_emails', function (Blueprint $table) {
            $table->dateTime('opened_at')->nullable();
        });
```

Then added an event listener. Only saves on the first open. If you want to track individual opens then you will need to add a secondary table like the sent_emails_url_clicked table

```
class ViewedMail
{
    /**
     * Handle the event.
     *
     * @param ViewEmailEvent $event
     * @return void
     */
    public function handle(ViewEmailEvent $event)
    {
        if (null == $event->sent_email->opened_at) {
            $event->sent_email->opened_at = Carbon::now();
            $event->sent_email->save();
        }
    }
}
```
