### ISSUE TITLE
Create relationship to the 'users' table

### ISSUE THREAD

**Issue by JerrelZendos** [jdavidbakr/mail-tracker#131]
Hello Jdavidbark,

First of all, thanks for this great package.

I was wondering, is there a way to create a relationship between the 'users' table and the 'sent_emails' table?

This would be useful to see which user received which emails.

Thanks!

**Comment by jdavidbakr** [comment]
This would be outside of the scope of this package (not everyone would have this need) but you could easily set up an observer on the SentEmails table and store the link in your own table.
