### ISSUE TITLE
Email Bounced not working

### ISSUE THREAD

**Issue by noprobz09** [jdavidbakr/mail-tracker#134]
Hi,

I created an event listener for tracking of clicks, views, open and bounce. The rest are working except the bounce event. 
Below is my code.

```
namespace App\Listeners;

use jdavidbakr\MailTracker\Events\PermanentBouncedMessageEvent;

class EmailBounced
{
    /**
     * Create the event listener.
     *
     * @return void
     */
    public function __construct()
    {
        
    }

    /**
     * Handle the event.
     *
     * @param  PermanentBouncedMessageEvent  $event
     * @return void
     */
    public function handle(PermanentBouncedMessageEvent $event)
    {
        // Access the email address using $event->email_address...
       \Log::info($event);
       \Log::info($event->email_address);
    }
}
```

Let me know what did I missed on the code. Thanks in advance.

**Comment by noprobz09** [comment]
By the way I am using Sendgrid as mail provider. Thanks :)

**Comment by jdavidbakr** [comment]
Bounced only works with SES right now.  If you want to flesh out how to do it with Sendgrid and submit a PR, please feel free.

**Comment by Ankitadeb** [comment]
Does bounce event work without Amazon SNS?

**Comment by jdavidbakr** [comment]
> Does bounce event work without Amazon SNS?

No.
