### ISSUE TITLE
Undefined property: stdClass::$notificationType

### ISSUE THREAD

**Issue by tmbn-dean** [jdavidbakr/mail-tracker#137]
Undefined property: stdClass::$notificationType

File: src/SNSController.php
Line: 57

Notifications coming from AWS are coming with "eventType" instead of "notificationType"

**Comment by jdavidbakr** [comment]
Also, looking at the docs you may not be properly setting up your SNS.

Wrong way: https://docs.aws.amazon.com/ses/latest/DeveloperGuide/event-publishing-retrieving-sns-contents.html

Right way: https://docs.aws.amazon.com/ses/latest/DeveloperGuide/notification-contents.html

**Comment by kapletiya** [comment]
Hi, I am facing same issue.
I have setup SNS using below URL
https://docs.aws.amazon.com/ses/latest/DeveloperGuide/configure-sns-notifications.html

the json I am receiving is

> {
  "Type" : "Notification",
  "MessageId" : "7eb0e7c9-87a1-57ee-b7ab-be079b92dbd4",
  "TopicArn" : "arn:aws:sns:eu-west-1:060631304280:campaign-mail-notifications-2",
  "Subject" : "Amazon SES Email Event Notification",
  "Message" : "{\"eventType\":\"Delivery\",\"mail\":{\"timestamp\":\"2021-09-29T07:46:58.471Z\",\"source\":\"hello@telsamedia.com\",\"sourceArn\":\"arn:aws:ses:eu-west-1:060631304280:identity/hello@telsamedia.com\",\"sendingAccountId\":\"060631304280\",\"messageId\":\"0102017c30855b27-4dabfe8f-e0c5-495f-9f4e-d75ee114909a-000000\",\"destination\":[\"brijesh@telsamedia.com\"],\"headersTruncated\":false,\"headers\":[{\"name\":\"Message-ID\",\"value\":\"<a7cf83b65b18766a49c6eaab829dfd06@ec2-35-176-93-221.eu-west-2.compute.amazonaws.com>\"},{\"name\":\"Date\",\"value\":\"Wed, 29 Sep 2021 07:46:58 +0000\"},{\"name\":\"Subject\",\"value\":\"Send Campaign Email\"},{\"name\":\"From\",\"value\":\"Telagus <hello@telsamedia.com>\"},{\"name\":\"To\",\"value\":\"brijesh@telsamedia.com\"},{\"name\":\"MIME-Version\",\"value\":\"1.0\"},{\"name\":\"Content-Type\",\"value\":\"text/html; charset=utf-8\"},{\"name\":\"Content-Transfer-Encoding\",\"value\":\"quoted-printable\"},{\"name\":\"X-SES-CONFIGURATION-SET\",\"value\":\"campain_mail_notifications\"},{\"name\":\"X-Model-ID\",\"value\":\"22\"},{\"name\":\"X-Mailer-Hash\",\"value\":\"hnLiKPw3TPFicwjYI5M2fb7Qw7BCNxMp\"}],\"commonHeaders\":{\"from\":[\"Telagus <hello@telsamedia.com>\"],\"date\":\"Wed, 29 Sep 2021 07:46:58 +0000\",\"to\":[\"brijesh@telsamedia.com\"],\"messageId\":\"0102017c30855b27-4dabfe8f-e0c5-495f-9f4e-d75ee114909a-000000\",\"subject\":\"Send Campaign Email\"},\"tags\":{\"ses:operation\":[\"SendRawEmail\"],\"ses:configuration-set\":[\"campain_mail_notifications\"],\"ses:source-ip\":[\"35.176.93.221\"],\"ses:from-domain\":[\"telsamedia.com\"],\"ses:caller-identity\":[\"brijesh@telsamedia.com\"],\"ses:outgoing-ip\":[\"54.240.7.11\"]}},\"delivery\":{\"timestamp\":\"2021-09-29T07:46:59.083Z\",\"processingTimeMillis\":612,\"recipients\":[\"brijesh@telsamedia.com\"],\"smtpResponse\":\"250 2.0.0 OK  1632901619 v12si1592491wrr.350 - gsmtp\",\"reportingMTA\":\"a7-11.smtp-out.eu-west-1.amazonses.com\"}}\n",
  "Timestamp" : "2021-09-29T07:46:59.159Z",
  "SignatureVersion" : "1",
  "Signature" : "bvYqmiZGLnJzx89I0KzDMRx5+vHCcQPuPVLptvMmSIaB/np7W5habUNIugbsRAxgoQhcldyMDP7kOH5d5ZkIWYsW4UHeylwfJHH+QQn1r4H0zNF1v4o43QrSVl9WH1lLJpfYbO23mlqMQyY8OGrHrq+vkIrVK9XGfm5kog2Sp87rsNuHSCGzzxh4x8CWC7zBtKFnaYzC5ECNmawLvthm+P0XYeweXWyhxQk3PFFh55EPIVU7jchpHNzp9QA/jkrI1Ywr3d8eySdA2qxK/hTZDz2oR0OF0Rmj0yM7W16JFLfXcD5y6noNR2I1a8LqLlYJHnYbmLpgt94WQ/s8zFd8iQ==",
  "SigningCertURL" : "https://sns.eu-west-1.amazonaws.com/SimpleNotificationService-7ff5318490ec183fbaddaa2a969abfda.pem",
  "UnsubscribeURL" : "https://sns.eu-west-1.amazonaws.com/?Action=Unsubscribe&SubscriptionArn=arn:aws:sns:eu-west-1:060631304280:campaign-mail-notifications-2:9b55add9-8949-4c0b-8aea-3e5c2e9e861c"
}

**Comment by jdavidbakr** [comment]
See my above comment and make sure that you are subscribed to notifications and not events.

**Comment by kapletiya** [comment]
Yes, I have subscribed to notifications only. The only thing I had to update is replace "notificationType" with "eventType" in the code to make it working. Thanks.
