### ISSUE TITLE
Disabled link tracking after 20k emails sent. Now all clicks are broken.

### ISSUE THREAD

**Issue by danpalmieri** [jdavidbakr/mail-tracker#138]
Any help to not validate hash when link tracking is disabled?

**Comment by jdavidbakr** [comment]
Not sure why that would be happening.  If you have link tracking disabled, then the email that gets sent should not have any links modified.  Have you looked at the source of the sent email to see what has happened to the links?

**Comment by danpalmieri** [comment]
First, it was activated. So the links were sent with tracking.
After send 20k emails with tracking activated, I deactivated.

So all link sent before are broken.

**Comment by jdavidbakr** [comment]
Did you purge the sent_emails table?  The previous links should continue to work as long as the emails are still in that table.

**Comment by danpalmieri** [comment]
Yes. The table was gone. I think it would be nice to, even if the tracking was not found, if the tracking is disabled, just redirect it to the ?l=https:// parameter.

**Comment by jdavidbakr** [comment]
That makes sense.  Fixed in [5.0.2](https://github.com/jdavidbakr/mail-tracker/releases/tag/5.0.2)
