### ISSUE TITLE
SentMail created after SES exception

### ISSUE THREAD

**Issue by dnyfs** [jdavidbakr/mail-tracker#139]
When an SES exception occurs when sending an e-mail, above the daily sending quota for example, even so a record is created in the sent_mail table.

This record should not exist, since the email was not sent.

I verified that it is not possible to disable this creation, do you think about adjusting this?

**Comment by jdavidbakr** [comment]
I don't know if I would be able to since the exception is happening outside of this plugin.  Open to ideas.

**Comment by edsonalvesan** [comment]
I'm having the same problem, sending the email is registered in the sent_emails table but it doesn't reach the recipient, in my case it's not quota limit, it's as if SES doesn't receive the request or doesn't deliver.

I'm using version 3.0

If anyone has any light to look for, because I don't know what else to do.

**Comment by jdavidbakr** [comment]
@edsonalvesan is an exception being thrown?  Does it work without this package?  If there is no exception my guess is that it is something unrelated to this package.

**Comment by edsonalvesan** [comment]
> @edsonalvesan is an exception being thrown? Does it work without this package? If there is no exception my guess is that it is something unrelated to this package.

@jdavidbakr  has no exception being launched, which I find strange, simply the emails do not reach the recipient.

**Comment by jdavidbakr** [comment]
@edsonalvesan does it work without this package?

**Comment by edsonalvesan** [comment]
> does it work without this package?

Also no, I have the same non-delivery problem, I don't believe the problem with this in the package, my doubt was more that I would have any idea where to look for the root of the problem

**Comment by jdavidbakr** [comment]
Ok, this issue is out of scope for this issue tracker.  Might try the Laravel Slack channel or one of the Laravel forums.
