### ISSUE TITLE
View Email not tracking

### ISSUE THREAD

**Issue by kamonth88** [jdavidbakr/mail-tracker#141]
I created EmailSendListener , It's work but when i created EmailViewListenter to track a user open email. it's not working (I add getHeaders()->addTextHeader('X-Model-ID',$send_mail->id)) 
how to solve ?

**Comment by jdavidbakr** [comment]
You could manually fire the event in Tinker and make sure the event listener is working.  Most likely it's not installed correctly.  Unfortunately there's not much to go on from your comment.
