### ISSUE TITLE
How to handle AWS SES Bounce emails?

### ISSUE THREAD

**Issue by vish4395** [jdavidbakr/mail-tracker#142]
I registered SNS subscription on my /email/sns route
but I am unable to get bounce & complaint status

**Comment by jdavidbakr** [comment]
Unfortunately I'm not able to offer technical support in this forum.  Be sure that the notifications are arriving and if so, see if you can file a specific bug report.  If they are not arriving to the subscription then you will need to figure out how to resolve that, which is outside of the scope of the github issue tracker.
