### ISSUE TITLE
Upgrade to Guzzle 7 because it's not compatible with Laravel 8.4

### ISSUE THREAD

**Issue by LonnyX** [jdavidbakr/mail-tracker#143]
I am not able to install this package in a Laravel 8.4 applications.

This is what I have : 
![image](https://user-images.githubusercontent.com/10662320/127707437-5d81aedb-6710-4f3e-95d6-f1f5bafe4982.png)

**Comment by jdavidbakr** [comment]
I think this is another issue outside of this package, I have it installed just fine with a project using Guzzle 7.3.0 and Laravel 8.52.

**Comment by Stiropor** [comment]
Same thing just happened to me using Laravel v8.51

**Comment by LonnyX** [comment]
@Stiropor I fixed this by removing completely `composer.lock` & `/vendor`

**Comment by Stiropor** [comment]
Thanks @LonnyX this worked perfectly. This package is awesome!
