### ISSUE TITLE
Undefined property: stdClass::$diagnosticCode

### ISSUE THREAD

**Issue by markimpmc** [jdavidbakr/mail-tracker#144]
Today the following exception was thrown:
`Undefined property: stdClass::$diagnosticCode`

in the file jdavidbakr/mail-tracker/src/RecordBounceJob.php line 73

Searching the AWS SNS documentation, apparently, the diagnosticCode property is not always sent:

> diagnosticCode
> 
> The status code issued by the reporting MTA. This is the value of the Diagnostic-Code field from the DSN. This field may be absent in the DSN (and therefore also absent in the JSON).
> 

The following is an example of a bounce object.

```json
{
   "bounceType":"Permanent",
   "bounceSubType": "General",
   "bouncedRecipients":[
      {
         "status":"5.0.0",
         "action":"failed",
         "diagnosticCode":"smtp; 550 user unknown",
         "emailAddress":"recipient1@example.com"
      },
      {
         "status":"4.0.0",
         "action":"delayed",
         "emailAddress":"recipient2@example.com"
      }
   ],
   "reportingMTA": "example.com",
   "timestamp":"2012-05-25T14:59:38.605Z",
   "feedbackId":"000001378603176d-5a4b5ad9-6f30-4198-a8c3-b1eb0c270a1d-000000",
   "remoteMtaIp":"127.0.2.0"
}
```

**Comment by jdavidbakr** [comment]
Thanks for the catch - fixed in [5.0.5](https://github.com/jdavidbakr/mail-tracker/releases/tag/5.0.5)
