### ISSUE TITLE
Class path.storage does not exist

### ISSUE THREAD

**Issue by marcemarin** [jdavidbakr/mail-tracker#146]
When i run migrate i get this message "Class path.storage does not exist", i folow the instructions, please help me

**Comment by jdavidbakr** [comment]
I've never seen that exception.  Can you get the backtrace?  What version of Laravel?

**Comment by marcemarin** [comment]
thanks for answer, i'm usign Lumen , here's the backtrace
[previous exception] [object] (ReflectionException(code: -1): Class
path.storage does not exist at
/app/vendor/laravel/framework/src/Illuminate/Container/Container.php:803)
[stacktrace]
#0
/app/vendor/laravel/framework/src/Illuminate/Container/Container.php(803):
ReflectionClass->__construct('path.storage')
#1
/app/vendor/laravel/framework/src/Illuminate/Container/Container.php(681):
Illuminate\\Container\\Container->build('path.storage')
#2
/app/vendor/laravel/framework/src/Illuminate/Container/Container.php(629):
Illuminate\\Container\\Container->resolve('path.storage', Array)
#3 /app/vendor/laravel/lumen-framework/src/Application.php(274):
Illuminate\\Container\\Container->make('path.storage', Array)
#4
/app/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(120):
Laravel\\Lumen\\Application->make('path.storage', Array)
#5
/app/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(841):
app('path.storage')
#6 /app/vendor/laravel/lumen-framework/config/logging.php(45):
storage_path('logs/lumen.log')
#7 /app/vendor/laravel/lumen-framework/src/Application.php(666):
require('/app/vendor/lar...')
#8 /app/vendor/laravel/lumen-framework/src/Application.php(463):
Laravel\\Lumen\\Application->configure('logging')
#9
/app/vendor/laravel/framework/src/Illuminate/Container/Container.php(799):
Laravel\\Lumen\\Application->Laravel\\Lumen\\{closure}(Object(Laravel\\Lumen\\Application),
Array)
#10
/app/vendor/laravel/framework/src/Illuminate/Container/Container.php(681):
Illuminate\\Container\\Container->build(Object(Closure))
#11
/app/vendor/laravel/framework/src/Illuminate/Container/Container.php(629):
Illuminate\\Container\\Container->resolve('Psr\\\\Log\\\\LoggerI...', Array)
#12 /app/vendor/laravel/lumen-framework/src/Application.php(274):
Illuminate\\Container\\Container->make('Psr\\\\Log\\\\LoggerI...', Array)
#13
/app/vendor/sentry/sentry-laravel/src/Sentry/Laravel/ServiceProvider.php(60):
Laravel\\Lumen\\Application->make('Psr\\\\Log\\\\LoggerI...')
#14 /app/vendor/laravel/lumen-framework/src/Application.php(207):
Sentry\\Laravel\\ServiceProvider->register()
#15 /app/bootstrap/app.php(22):
Laravel\\Lumen\\Application->register(Object(Sentry\\Laravel\\ServiceProvider))
#16 /app/public/index.php(13): require('/app/bootstrap/...')
#17 {main}
"}

**Comment by jdavidbakr** [comment]
I've not vetted this with Lumen, so I can't speak to whether it will work with Lumen and technically am only supporting Laravel proper.

**Comment by marcemarin** [comment]
Ok, thank you for your answer.
