### ISSUE TITLE
Give tracking events access to IP address

### ISSUE THREAD

**Issue by jdavidbakr** [jdavidbakr/mail-tracker#151]
See https://github.com/jdavidbakr/mail-tracker/issues/64#issuecomment-963095939

**Comment by jdavidbakr** [comment]
Added in https://github.com/jdavidbakr/mail-tracker/releases/tag/5.0.6

**Comment by tormjens** [comment]
Awesome! Thanks for the quick implementation ;) I'll give it a test-drive, but looks like it will do just perfect :D
