### ISSUE TITLE
Version update request for laravel 9 

### ISSUE THREAD

**Issue by PositiveZahid** [jdavidbakr/mail-tracker#162]
I have updated my project from laravel 8 to laravel 9. I had to remove this package temporarily during this update process. But I am not able to re-install this package, because it is conflicting with illumiate/support version. I think laravel core has updated dependency for illumiate/support. 

jdavidbakr/mail-tracker[5.0.0, ..., 5.0.9] require illuminate/support ~7.0|~8.0 -> found illuminate/support[v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev] but these were not loaded, likely because it conflicts with another require.

**Comment by jdavidbakr** [comment]
See https://github.com/jdavidbakr/mail-tracker/issues/155 - With Laravel 9 they changed away from SwiftMailer and I have not been able to figure out how to accomplish this plugin via Symfony's mailer.  Looking for help from anyone who might know how to do it.
