### ISSUE TITLE
Error after upgrading to v6.0

### ISSUE THREAD

**Issue by danpalmieri** [jdavidbakr/mail-tracker#166]
I'm getting this error when sending emails:
`Call to undefined method Symfony\Component\Mime\Part\Multipart\AlternativePart::getBody()`

When I disable the mail-tracker package, is all normal.
Any tips?

Error log: https://flareapp.io/share/NPL9xyg7#F80

Thanks!

**Comment by jdavidbakr** [comment]
@danpalmieri - thanks for the patch!  6.0.1 has been released.
