### ISSUE TITLE
Message sends as file (not as html) v.6.0.1

### ISSUE THREAD

**Issue by rommeA** [jdavidbakr/mail-tracker#168]
Thanks for the quik fix for v.6.0. 
I've upgraded to v.6.0.1 and i'm getting this bug when sending an email.
![image](https://user-images.githubusercontent.com/62960969/161000503-3de14586-f44a-432c-99b7-5aa090e5453d.png)
This file actually contains original HTML of the message.
My code:
`Mail::to($email)->send(new NewLogin());`
in NewLogin.php:
```
    public function build()
    {
        return $this->markdown('emails.login.new');
    }
```
I think there's smth wrong with `setBody` method here (MailTracker.php):
```
$message->setBody(new TextPart(
                            $this->addTrackers($original_html, $hash),
                            null,
                            $original_content->getMediaSubtype(),
                            null
                        )
                    );
```

**Comment by rommeA** [comment]
Yeah, clearly the problem is in calling the `setBody ` method - I commented it and got correct message .

**Comment by rommeA** [comment]
upd: works fine with this:
```
$message->setBody(
                        new TextPart(
                            $this->addTrackers($original_html, $hash),
                            $message->getHtmlCharset(),
                            'html'
                        ));
```

original subtype was "alternative", but for proper work it needs to be changed to "html"...

**Comment by jdavidbakr** [comment]
Ok, seems that the issue is the structure of the messages is a bit more complicated than it was with SwiftMailer.  I've made some more adjustments in 6.0.2 and extended the test case coverage.  Please continue to report any issues in 6.0.x that come up as they are found.
