### ISSUE TITLE
Opens/Clicks counter always 0

### ISSUE THREAD

**Issue by rommeA** [jdavidbakr/mail-tracker#169]
Date & time of the first view are saving correctly, but number of opens is always zero. 
![image](https://user-images.githubusercontent.com/62960969/161247751-af8b4939-31d9-4b03-8620-d5f003689eae.png)

URL for tracking pixel generates correctly: 
![image](https://user-images.githubusercontent.com/62960969/161248589-ca42a826-d5e3-4f1f-b6e4-6430a150406a.png)
When I open the url in browser, 'opens' counter stays 0.

P.S.: I use jdavidbakr/mail-tracker v.6.0.2

P.P.S.: this bug repeats with 'clicks' counter

**Comment by rommeA** [comment]
upd: forgot to run the queue.

**Comment by bilogic** [comment]
thanks, saved me from opening an issue
