### ISSUE TITLE
Subject empty in DB when it has emoji

### ISSUE THREAD

**Issue by andrew-za** [jdavidbakr/mail-tracker#17]
When I use a emoji in the email subject the subject is stored emtpy into DB

**Comment by bretto36** [comment]
Possibly can't convert the subject to a 255 character string?

**Comment by jdavidbakr** [comment]
@andrew-za - can you post the code that is composing the email, or at least assigning the subject?  Most likely it's an eloquent issue that is preventing the subject to get parsed as a string, as @bretto36 suggests.

**Comment by jdavidbakr** [comment]
Due to lack of follow up response, I am closing this issue.
