### ISSUE TITLE
Installation Fails

### ISSUE THREAD

**Issue by karandatwani92** [jdavidbakr/mail-tracker#171]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires jdavidbakr/mail-tracker 6.* -> satisfiable by jdavidbakr/mail-tracker[6.0, 6.0.1, 6.0.2].
    - jdavidbakr/mail-tracker[6.0, ..., 6.0.2] require illuminate/support ~9.0 -> found illuminate/support[v9.0.0-beta.1, ..., 9.x-dev] but these were not loaded, likely because it conflicts with another require.
    
#### PHP VERSION:
PHP 8.1.2 (cli) (built: Jan 19 2022 10:18:23) (ZTS Visual C++ 2019 x64)
Copyright (c) The PHP Group
Zend Engine v4.1.2, Copyright (c) Zend Technologies

#### LARAVEL VERSION:
v8.83.7@0706abf5c99d3b14149fcf79c95074dadd40b203

> Other packages with the same requirement "require illuminate/support ~9.0" are installed and working.

**Comment by jdavidbakr** [comment]
For Laravel < 9 you need to use version 5.*.  There was a fundamental change in Laravel 9 that completely changed the way it sends mail, and this package had to be rewritten for Laravel >= 9.
