### ISSUE TITLE
[6.0] MixedPart messages cause exception

### ISSUE THREAD

**Issue by avdb** [jdavidbakr/mail-tracker#172]
I get the same error as https://github.com/jdavidbakr/mail-tracker/pull/167 but then for MixedPart mime part.
Shared my error below.
Looks like `if(get_class($original_content) == AlternativePart::class) {` should be also for the mixedPart ?
`Call to undefined method Symfony\Component\Mime\Part\Multipart\MixedPart::getBody()`

I assume it's because we add a file to the message.

https://flareapp.io/share/omwaojZ7#F120

The code I use to send a mail:

```
return (new MailMessage())
    ->subject(config('app.name'))
    ->line($line)
    ->attach(storage_path('app/'.$this->fileName));
```

**Comment by jdavidbakr** [comment]
See if https://github.com/jdavidbakr/mail-tracker/releases/tag/6.0.3 fixes it

**Comment by avdb** [comment]
awesome thanks!
