### ISSUE TITLE
Lazy Loading Issue

### ISSUE THREAD

**Issue by usernotnull** [jdavidbakr/mail-tracker#180]
I usually disable lazy loading to spot performance bottlenecks, ie:

```php
Model::preventLazyLoading();
```

I'm checking your `awesome` library :) In the URL report, I'm getting the following error:

```
Attempted to lazy load [email] on model [jdavidbakr\MailTracker\Model\SentEmailUrlClicked] but lazy loading is disabled.
```

Worth noting that this is happening when, in the email, more than 1 unique link is clicked (2 or more links-clicked rows will cause the error).

You can view the full report here to see the stack trace: https://flareapp.io/share/NPL9npQ7#F81

(see resources/views/vendor/emailTrakingViews/url_detail.blade.php:17)

**Comment by jdavidbakr** [comment]
Fixed in [6.0.5](https://github.com/jdavidbakr/mail-tracker/releases/tag/6.0.5)
