### ISSUE TITLE
Disable link tracking for a specific link

### ISSUE THREAD

**Issue by UtkuDalmaz** [jdavidbakr/mail-tracker#196]
I would like to disable tracking for a specific link. Any way to do that?

If no, please take it as a feature request.

Thanks

**Comment by jdavidbakr** [comment]
No, there's no way to blacklist a link at this time, but I could see it maybe being done with an attribute in the anchor tag, i.e. `<a href="example.com" data-mailtracker-notrack="true">` - feel free to make a PR as it probably won't be a high priority on my end.

**Comment by UtkuDalmaz** [comment]
I have zero regex knowledge, how can I exclude `data-mailtracker-notrack="true"` from this regex` /(<a[^>]*href=[\"])([^\"]*)/` would you help a bit?

**Comment by UtkuDalmaz** [comment]
@jdavidbakr any time to implement this little feature?
