### ISSUE TITLE
Mail body is duplicated when using a attachment.

### ISSUE THREAD

**Issue by svenvanhees** [jdavidbakr/mail-tracker#197]
Started a new Laravel 9 project.
Setup Mailtrap.io mailer.
Installed the mail tracker package.
Created a test mail.
Send the test mail with tinker.
Email received, but the html content is duplicated.

![image](https://user-images.githubusercontent.com/3237025/190622197-371dee18-0027-429b-aae7-0c6df95bfbd9.png)

\App\Mail\Test.php
```
<?php

namespace App\Mail;

use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Mail\Mailable;
use Illuminate\Queue\SerializesModels;

class Test extends Mailable
{
    use Queueable, SerializesModels;

    /**
     * Create a new message instance.
     *
     * @return void
     */
    public function __construct()
    {
        //
    }

    /**
     * Build the message.
     *
     * @return $this
     */
    public function build()
    {
        return $this
            ->markdown('mail::message')
            ->with([ 'slot' => 'Testing' ])
            ->attachData('Testing', "testing.txt");
    }
}
```
`Mail::to('testing@test.com')->send(new \App\Mail\Test());`

**Comment by svenvanhees** [comment]
I think #183 is causing this problem. Commenting that piece of code, results in a normal email with attachment.

**Comment by svenvanhees** [comment]
Suggest to approve #198 @jdavidbakr to resolve this issue.

**Comment by jdavidbakr** [comment]
PR merged and released
