### ISSUE TITLE
Class super does not exist

### ISSUE THREAD

**Issue by paulchill** [jdavidbakr/mail-tracker#20]
Hi,

I am trying to use your package. i get this error "Class super does not exist" when calling any admin routes.

if i comment out super in mail-tracker.php it appears to work but then when i click view none of those views work.

I am on laravel 5.2.45 and i installed version "jdavidbakr/mail-tracker": "~2.0". and Ran vendor publish
created a route and points too:
 Route::get('/email-manager', function()
    {
        return view('mailTracker_Index');
    });

Am i missing anything?

Great package btw 👍

**Comment by jdavidbakr** [comment]
In the config file, set the appropriate middleware for your user who has access to the back-end.  It's set to 'super' by default which is not a standard middleware, just to ensure that you don't accidentally give access to the wrong group.

**Comment by paulchill** [comment]
Ok great i get you thanks for the help! is one view used to see the data from both tables?

**Comment by jdavidbakr** [comment]
There is one view that is an overview and a second view that is the detail view.  But you are more than welcome to modify these views to suit your needs.

**Comment by paulchill** [comment]
Thanks 👍  i have an angular site and i am rendering the index for any non route,  could you tell me the route which the email tracking takes ?  as i am having problems with using this with the angular any etc

**Comment by jdavidbakr** [comment]
It's all configurable in the config file.
