### ISSUE TITLE
Hi,  I have created an event listener for tracking of clicks, views, open and bounce. But bounce event is not working.

### ISSUE THREAD

**Issue by Ankitadeb** [jdavidbakr/mail-tracker#207]
<?php

namespace App\Listeners;

use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Queue\InteractsWithQueue;
use jdavidbakr\MailTracker\Events\PermanentBouncedMessageEvent;

class BouncedEmail
{
    /**
     * Create the event listener.
     *
     * @return void
     */
    public function __construct()
    {
        //
    }

    /**
     * Handle the event.
     *
     * @param  PermanentBouncedMessageEvent  $event
     * @return void
     */
    public function handle(PermanentBouncedMessageEvent $event)
    {
       \Log::info($event);
       

    }
}

**Comment by jdavidbakr** [comment]
Unfortunately this is not a support forum, if there is an actual reproducible issue please indicate the steps to reproduce.  Bounce event requires SNS feedback.
