### ISSUE TITLE
Complaint Data not Received mark as Spam and Remove, not received any response. 

### ISSUE THREAD

**Issue by deepakbizinso** [jdavidbakr/mail-tracker#216]

**Comment by jdavidbakr** [comment]
Need significantly more detail to make this an actionable issue.

**Comment by deepakbizinso** [comment]
Please Response a need full help.

**Comment by jdavidbakr** [comment]
Unfortunately this is not the forum for tech support, and I don't have the bandwidth to provide tech support.  Be sure your SES notifications are properly set up, this feature only works with SES.
