### ISSUE TITLE
Migration fails on mysql 5.6.21

### ISSUE THREAD

**Issue by stevenmyhre** [jdavidbakr/mail-tracker#22]
The newest migration ```2016_11_10_213551_add-message-id-to-sent-emails-table.php``` doesn't work on my mysql version, with error:

    SQLSTATE[42000]: Syntax error or access violation: 1101 BLOB/TEXT column 'meta' can't have a default value (SQL: alter table `sent_emails` add `message_id` varchar(255) null, add `meta` text not null default '[]')

I don't think we should need a default value, right?

**Comment by jdavidbakr** [comment]
PR merged
