### ISSUE TITLE
MASSIVE Security Issue

### ISSUE THREAD

**Issue by brycematheson** [jdavidbakr/mail-tracker#227]
When this package is installed, http://<domainname>.com/email/n?l=https%3A%2F%2Fbafkreia3npf5ze77wak4mvqezytipp2fbmhikq5w3bshbdfx2zz72krdsi.ipfs.dweb.link%2F%3Ffilename%3Dana.html#kelly@trypotstudios.com

redirects to:

https://bafkreia3npf5ze77wak4mvqezytipp2fbmhikq5w3bshbdfx2zz72krdsi.ipfs.dweb.link/?filename=ana.html#kelly@trypotstudios.com

I finally discovered the issue, but my site was down for 48 hours due to my domain registrar suspending our domain for abuse/phishing. Please fix ASAP.

**Comment by sync667** [comment]
That is not right if i'm not wrong in my checks problem has to be on your side. Function that parse that redirect do not have any injects other that url you have in your emails or default that is in config. So i is possible that you had security problem on other side so you app sends emails with that phishing links not the plugin itself.

**Comment by brycematheson** [comment]
I can't believe this is still not resolved. I've loved using the package in the past, and would like to continue using it going forward, but not until this is fixed. It's taken me months to get whitelisted with ISPs again because of the breach.

**Comment by jdavidbakr** [comment]
PR's are always appreciated.  Unfortunately I'm spread too thin at the moment to address this.

**Comment by jdavidbakr** [comment]
This was addressed in a recent update.
