### ISSUE TITLE
Call to undefined method Illuminate\Events\Dispatcher::fire() in Laravel 5.8

### ISSUE THREAD

**Issue by DanielCorrea245** [jdavidbakr/mail-tracker#231]
Laravel 5.8 is not using anymore the method fire(). Instead, it uses dispatch().

**Comment by jdavidbakr** [comment]
What version are you using that's till using `fire()`?

**Comment by DanielCorrea245** [comment]
5.0.9

**Comment by jdavidbakr** [comment]
I don't see a call to `fire()` in 5.0.9, where is this happening?

**Comment by jdavidbakr** [comment]
Closing due to lack of response
