### ISSUE TITLE
SNS message type header not provided.

### ISSUE THREAD

**Issue by UtkuDalmaz** [jdavidbakr/mail-tracker#243]
Hello,

I deployed a new project to Laravel Vapor (with octane support activated), and I started getting the "SNS message type header not provided." error from SNSController.php:34 when AWS SNS sends the bounce signal. 

I didn't get this error when the project was working on a traditional server (EC2 - octane installed)

Any idea about it?

Thanks

**Comment by jdavidbakr** [comment]
No ... it sounds like Vapor may be filtering incoming headers?

**Comment by UtkuDalmaz** [comment]
I tried with commenting this part

/**if (!isset($_SERVER['HTTP_X_AMZ_SNS_MESSAGE_TYPE'])) {
                throw new \RuntimeException('SNS message type header not provided.');
            }**/

And it worked that way. I guess $_SERVER is not available in Lambda environment.
So how to update that code to cover also Vapor users?

**Comment by jdavidbakr** [comment]
This is the discussion of why that's there:
https://github.com/jdavidbakr/mail-tracker/issues/149#issuecomment-1488929081

I don't use Octane so don't want to take it out without in being verified that it doesn't break, ideally with a test of some sort.

**Comment by UtkuDalmaz** [comment]
I know it, but this is a different topic. My point is about the Laravel Vapor / Lambda serverless environment.
$_SERVER is unavailable; that code breaks it when used in Vapor.
You can use a config value called vapor = true or false; if the user uses the Vapor, then he sets it to true.

and then in code, a small check sth like;

```
if (!config("vapor")) {
if (!isset($_SERVER['HTTP_X_AMZ_SNS_MESSAGE_TYPE'])) {
throw new \RuntimeException('SNS message type header not provided.');
}
```

**Comment by jdavidbakr** [comment]
I'm just saying that the check was introduced in that Octane ticket.  I didn't add that one, so I don't know if it's really necessary; feel free to submit a PR without it.  I would expect that if the SNS library needs that and doesn't see it that it would throw its own exception.

**Comment by UtkuDalmaz** [comment]
Opened the PR. Thanks
https://github.com/jdavidbakr/mail-tracker/pull/244

**Comment by jdavidbakr** [comment]
Thanks - closed and released
