### ISSUE TITLE
Migration files not published

### ISSUE THREAD

**Issue by PierreLebedel** [jdavidbakr/mail-tracker#245]
Hi! 
I use the current version 7.14.
When I run `php artisan vendor:publish --provider="jdavidbakr\MailTracker\MailTrackerServiceProvider"`, the config file and the views are published, but not the migration files.
I didn't realize it during development, because the tables had been created (how?), but I don't have the files in database/migrations.
Thanks!

**Comment by jdavidbakr** [comment]
Laravel doesn't require publishing the migration files, they are registered in the service provider and run with the other migrations.
