### ISSUE TITLE
Emails are not tracked in production

### ISSUE THREAD

**Issue by latomate07** [jdavidbakr/mail-tracker#247]
Hello,
First of all, I'd like to congratulate you on your fantastic package. It literally took me less than 2 minutes to activate it on my laravel application.
But I have a problem that I can't solve. Why does local email tracking work fine but not in production?
In fact, it's the email opening event that doesn't work in production, but clicking on links does work in production.
If anyone has a solution to my problem, please share it with me.

Yours faithfully

**Comment by jdavidbakr** [comment]
Unfortunately I cannot provide technical support via issues.  Your best course of action is to understand how the tracking is happening and identify why it's not working in production.
