### ISSUE TITLE
Mail hash is not uniquely generated

### ISSUE THREAD

**Issue by stevenmyhre** [jdavidbakr/mail-tracker#25]
[MailTracker.php#L122](https://github.com/jdavidbakr/mail-tracker/blob/master/src/MailTracker.php#L122)

The hash being generated is using ```str_random``` which internally uses php function [random_bytes](http://php.net/manual/en/function.random-bytes.php).

This function, although 32 length, could still have a collision, since it does not generate unique values. As such, the database unique constraint would fail and therefore the Mail would fail to send at all.

I suggest either using a uniquely generated hash (perhaps a hash off of the time or the database IDs).

Otherwise, we should probably catch the unique constraint exception and generate a new hash or just skip applying the tracking code to ensure the mail is successfully sent.

Open for discussion.

**Comment by jdavidbakr** [comment]
Fixed in #29
