### ISSUE TITLE
How to use same hash for multiple email

### ISSUE THREAD

**Issue by network211** [jdavidbakr/mail-tracker#27]
This library is exactly what I have been looking for! Great work. Save me piles of programming!

My question is: 
**How to use the same open hash for a group of email.** 

I am sending out a newsletter to multiple addresses. I really don't need to know about the open or click through for each individual addressee. I would like to know how many were opened. (Like Mailchimp or iContact).

**Comment by jdavidbakr** [comment]
Probably the best way to handle it would be to add a custom header (maybe the newsletter ID) and use the event hooks to track which sent email records map to which newsletter.  That's really the purpose of the events - you have a sent email event as well as a read email event.  There's an example in the readme that describes this strategy.
