### ISSUE TITLE
Another typo in index.php

### ISSUE THREAD

**Issue by karmendra** [jdavidbakr/mail-tracker#31]
In mail-tracker/src/views/index.blade.php, Line 54,
`<a href="{{route('mailTracker_ShowEmail',$email->id)}}" target="_blank">`
shold really be, `<a href="{{route('mailTracker_SmtpDetail',$email->id)}}" target="_blank">`

Best Regards,
Karmendra

**Comment by karmendra** [comment]
Hi,
Apart from the above mentioned issue, I worked to have all the features of latest version of this package  for Laravel version 5.1. I want to release that as 2.0.2. Can I submit a PR for that?
(I had done all changes in my local, not yet modified my fork, will do it in a day).

Thanks,
Karmendra

**Comment by jdavidbakr** [comment]
Did you start with the 2.0.1 commit?  I've created a branch that you can submit your pull request into at commit cfe5c01

**Comment by karmendra** [comment]
Yes I started, 2.0.1 as the base. I found few more issues, I will submit separate issue for that. I am thinking instead of 2.0.2, I can make the latest version compatible for Laravel versions lower than 5.3.23.
