### ISSUE TITLE
Handelling OOTO response from AWS

### ISSUE THREAD

**Issue by karmendra** [jdavidbakr/mail-tracker#32]
According to [mailbox-simulator-for-the-amazon-simple-email-service](https://aws.amazon.com/blogs/aws/mailbox-simulator-for-the-amazon-simple-email-service/)
when I attempted to send mail to `ooto@simulator.amazonses.com`, it sent but after that email-manager is not working

**Comment by jdavidbakr** [comment]
Can you tell if the callback is crashing, or what the failure is?  Any errors in the logs?

**Comment by karmendra** [comment]
To recreate this issue,
1. send email to `ooto@simulator.amazonses.com`
2. reopen the email manager and you will get following error 
    ErrorException in SentEmail.php line 64:
    Undefined index: status

The reason for this is `meta` column in `sent_email` table is having following value, that is not having status defined
> {"smtpResponse":"250 2.6.0 Message received","success":false,"delivered_at":"2017-07-17T21:16:51.980Z","failures":[{"emailAddress":"OOTO <ooto@simulator.amazonses.com>"}]}

Basically it needs separate switch in `SNSController@process_notification` to handle out-of-the-office response from AWS SNS.

Hope this helps.

Thanks
K

**Comment by jdavidbakr** [comment]
Should be fixed in 2.1.10 and 2.0.3
