### ISSUE TITLE
Mail tracker at multi database for multitenant setup

### ISSUE THREAD

**Issue by nguyenhaiphan** [jdavidbakr/mail-tracker#38]
Hi @jdavidbakr,

I'm using a multi-databases setup for multi-tenants mode. Is there anyway to separate your migration to database\migrations, so I can further utilize those migrations to each tenant database ?

**Comment by jdavidbakr** [comment]
Once the migration is published you can move it wherever you wish; in fact, you don't have to publish it at all, you can just copy it into your own migration structure; as long as the tables exist and the model is able to access it (i.e. your multi-tenant middleware is properly initializing the database connection for the callbacks) it should work fine to have it in your separate tenant databases.

**Comment by devoncmather** [comment]
I have moved the migrations out of the app and into my tenant migrations folder, however, I see no straightforward way to prevent the package from auto migrating itself on the global DB, where it isn't needed. Migrating seems to be reading from the database folder in the package
