### ISSUE TITLE
Sending to multiple users, link tracking error

### ISSUE THREAD

**Issue by bretto36** [jdavidbakr/mail-tracker#40]
Hi there, love using this repo. Thanks so much for it 

I've just had an issue on our production server. We sent an email to multiple users at once, but when the links were clicked it couldn't find the correct details. 

I found that the links all had the wrong sent_email hash on them for most users. They all shared one user's sent_email entry hash. See below for circled hash, the recipient below that highlighted one in the snip was getting the error. It wasn't refactoring the link to match what it previously was, it was just attempting to add it straight to the database but couldn't because its longer than 255 characters. I have now changed it to send to each user individually, but would prefer to keep them grouped for speed of sending

![image](https://user-images.githubusercontent.com/6217994/30938375-2c594f4e-a41d-11e7-81e9-996c1b1c9e53.png)

Illuminate\Database\QueryException: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'url' at row 1 (SQL: insert into `sent_emails_url_clicked` (`sent_email_id`, `url`, `hash`, `updated_at`, `created_at`) values (10683, ....

**Comment by bretto36** [comment]
After changing the URL column in the database to a TEXT column it fixed the error we were getting and the links still work. So not sure if we should create a migration that does that change or not

**Comment by jdavidbakr** [comment]
I will change the base migration to be TEXT in the next release.
