### ISSUE TITLE
Using this event PermanentBouncedMessageEvent

### ISSUE THREAD

**Issue by plazari15** [jdavidbakr/mail-tracker#42]
Hello, 
I'm trying to use this Event, PermanentBouncedMessageEvent but, i think the method don't gave me any data. 

I Passed this 

` public function handle(PermanentBouncedMessageEvent $event)
    {
        if($event && $event->email_address){
            $Email = EmailList::where('email', $event->email_address)->first();

            if($Email){
                $Email->tipo = 'blacklist';
                $Email->save();
            }
        }
    }`

What I'm doing wrong??

**Comment by jdavidbakr** [comment]
Fixed https://github.com/jdavidbakr/mail-tracker/releases/tag/2.1.16
