### ISSUE TITLE
option for not inserting the content / exception catching for content too long

### ISSUE THREAD

**Issue by vesper8** [jdavidbakr/mail-tracker#43]
For my newsletter which is very large and includes a lot of code.. I immediately ran into the "SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'content'" error

I was surprised since this is a text column, also I thought the default mysql behaviour was to show a warning but to insert the truncated value anyway.. but I guess not with Laravel.. or maybe that's changed.. anyway it's a fatal error

And now I find it difficult to curb this problem. I'm also sending thousands of newsletters and while I do want to track the opens/clicks on those.. it is not at all necessary for the content of the email to be inserted into the database since it's always the same content anyway

so how can I do that? And do you think maybe we could have an option to disable logging just the content column?

Thanks!

**Comment by jdavidbakr** [comment]
You could always make the field size larger (just update the field in the database); alternatively feel free to make that option and a pull request.

**Comment by vesper8** [comment]
ok thanks, I've added a PR
