### ISSUE TITLE
Error Authentication

### ISSUE THREAD

**Issue by GuiAndra** [jdavidbakr/mail-tracker#46]
Hello, i'm getting this error "Expected response code 250 but got code "530", with message "530 5.7.1 Authentication required " ".

I believe it's the email setup

To make my submissions, I need it to be different emails, so I set the email before sending it this way:

Config :: set ('mail.host', '$host');
Config :: set ('mail.username', \ Auth :: user () -> email);
Config :: set ('mail.password', \ Auth :: user () -> pass_email);
Config :: set ('mail.port', $port);
Config :: set ('mail.encryption', 'ssl');

I think this is generating the error

How can i fix this?

**Comment by jdavidbakr** [comment]
That seems a little convoluted, it seems that you're making it more complicated that you should.  At any rate, this sounds like a Laravel configuration issue, not an issue with this package - you might want to try asking at one of the Laravel community forums or in the Laravel slack channel.
