### ISSUE TITLE
Doesn't work with attachments

### ISSUE THREAD

**Issue by jspapp** [jdavidbakr/mail-tracker#53]
I'm trying to add attachments to a tracked email, but it doesn't seem to track opens anymore with attachments.

I'm using a markdown template which was working before adding attachments, so I'm not sure if that's related, but when I add any attachments, the tracking pixel isn't added and links aren't rewritten as tracked links.

**Comment by gabrielpeixoto** [comment]
when I send with attachments, the code doesn't execute:
  
```
foreach ($message->getChildren() as $part) {
    if (strpos($part->getContentType(), 'text/html') === 0) { 
        $part->setBody($this->addTrackers($message->getBody(), $hash)); // Cant enter here with attachments
    }
}
```

**Comment by gabrielpeixoto** [comment]
I think that have to allow **multipart/mixed** in:

```
if ($message->getContentType() === 'text/html' ||
     ($message->getContentType() === 'multipart/alternative' && $message->getBody())) {
         $message->setBody($this->addTrackers($message->getBody(), $hash));
}
```

**Comment by jdavidbakr** [comment]
Feel free to send a pull request, I will eventually get to look at this but it would probably happen faster if one of you guys were to do it.
