### ISSUE TITLE
Pixel tracking on gmail not working

### ISSUE THREAD

**Issue by lukaszog** [jdavidbakr/mail-tracker#54]
Hi,
I have problem with inject pixel for gmail. I send message with this pixel, but gmail not respond for this, in console I found `Failed to load resource: the server responded with a status of 404 ()` but when I grab link (only my link like `https://website.com/email/t/token`, not `https://ci6.googleusercontent.com/proxy/Lrwi0742pnJJ4eOu1No2MgrFh7Edt5jkPyx_kpbH4q9tJ1TT_SATOURtCkg1E9EC5ve3za2R4lybg49C_jOCWaYbmICNjFHaI_Jbjxolzogidw=s0-d-e1-ft#https://website.com/email/t/token` I put it into browser it's works.
Any one have the same problem?

**Comment by MadMikeyB** [comment]
Are you running on .dev or .test?

I've only seen this on development TLD's such as the above. Google doesn't like those, but dot com et al should all work fine?

**Comment by jdavidbakr** [comment]
Closing due to lack of response from OP

**Comment by ianrussel** [comment]
I also got issue in development machine running with .test. Does this work on production?

**Comment by jdavidbakr** [comment]
It's very possible that the dev locations don't work.  I've had occasional issues with some applications bypassing the valet DNS resolution, and also it's possible that gmail or other web clients are blocking .test or .dev.  I do use this every day in a production environment on multiple projects and have never had an issue, in fact I'm frequently going in to check to see whether someone received and email that they said they never received (90% of the time they not only received it but clicked on a link in it)

**Comment by ianrussel** [comment]
And also I don't know if with google adding proxy, something like "https://ci4.googleusercontent.com/proxy/KS_UvRC1wcPB4d1zRZOXRC2huJaYRggE07FiNo9MWQqHwMAykM2IpocjL7JIVBwlP4SoDoW4wn7Ix5jmxFKqDz5Zf78=s0-d-e1-ft#https://front-end.test/email/t/BJT153568141305" also works in production. I think this is the reason why it does not work on localhost.

**Comment by ianrussel** [comment]
I can confirm this works in production.  Many thanks @jdavidbakr

**Comment by jdavidbakr** [comment]
@ianrussel yeah, if Google is adding a proxy, obviously that proxy won't have access to your local domain.  Interesting to note.  Thanks for the report!

**Comment by jdavidbakr** [comment]
FWIW, if you use Mailtrap for development it will work correctly.
