### ISSUE TITLE
Ability to disable routes

### ISSUE THREAD

**Issue by Cannonb4ll** [jdavidbakr/mail-tracker#57]
Great package, just started using it.

Currently, the package provides a panel to see the sent emails and their statuses. Problem is that I don't need the routes as I want to display the e-mails in my own panel with my own route names.

Would be great to just disable these routes, currently I attach a middleware to them so the user gets redirected if they would ever 'gues' the url.

**Comment by jdavidbakr** [comment]
You can always just put a middleware on the `admin-route` config that rejects all requests.  The default `super` middleware is there to prevent just what you describe, since Laravel doesn't have a `super` middleware route by default.
