### ISSUE TITLE
possible to change which domains are used for the different routes?

### ISSUE THREAD

**Issue by vesper8** [jdavidbakr/mail-tracker#58]
I send all emails from api.mydomain.com

my front-end is located at www.mydomain.com

The absolute links I use inside my emails point to my front-end site. But by default this package was changing them to api.mydomain.com

I used URL::forceRootUrl to force it to www.mydomain.com and there I crearted a special /email catchall route that redirects to api.mydomain.com/email and performs the redirect and tracks the click

however for the SNS route I would like it to use api.mydomain.com because I don't want each email view to have to load my whole JS app

so how is it possible to customize the routes and which URLs that are bound to please?

**Comment by jdavidbakr** [comment]
I'm not sure I understand what you are trying to accomplish.  Do the emails have what you are looking for if you set `track-links` to false?  The only thing the tracker adds is in intermediary step that routes all the links through so that it can capture the clicks.  You have complete control over what this route is via the `route` setting in `config\mail-tracker.php` where you could specify the domain that is used for the pingback URL.

**Comment by vesper8** [comment]
@jdavidbakr it was my understanding that you also track the "email opens" using SNS ? How else is the "open" stat calculated?

This uses a pixel doesn't it? And this pixel also uses a route?

I'm asking if we can have a different route for the pixel then for the tracking

**Comment by jdavidbakr** [comment]
SNS just tracks delivery, not open.  Open is calculated via the pixel.  I'm not sure what the advantage to having a different route for the pixel vs the click tracking would be since both need to go to a point on your site to log the event.

**Comment by vesper8** [comment]
well in my case I simply don't want to expose the url. The pixel's URL is transparent and the user doesn't see where it goes (in my case I want it to be api.mydomain.com)

But the track url is very apparent when the user clicks on it, I feel that the user should not be clicking a link that takes them to an api.domain.com

**Comment by vesper8** [comment]
Well.. I'm not that worried about it, most users wouldn't notice the pixel url but would notice the other link when they hover over the links in my emails. If this is something that I can change myself I would like to do it. Do you think it would be difficult to allow for the track url and pixel url to be two different domains?

Thanks, appreciate the time

**Comment by jdavidbakr** [comment]
The easiest way would be to copy/extend the service provider in the package and change the route registration function, then you could have it do whatever you'd like. As long as the controllers are the same you'll get the same functionality.
