### ISSUE TITLE
Doesn't log Sent Emails on a multi user platform

### ISSUE THREAD

**Issue by stacybot123** [jdavidbakr/mail-tracker#59]
Hi,

I am trying to use the package with the Multiuser platform where every user has its own smtp setting. With a multiuser platform it doesn't logs the email sent. Here is the code I am using to send email:
```
               $transport = new Swift_SmtpTransport($smtp->trans, $smtp->port, $smtp->encr);
                $transport->setUsername($smtp->user_name);
                $transport->setPassword($smtp->password);
                $temp_sender= new Swift_Mailer($transport);
                Mail::setSwiftMailer($temp_sender);
        
                Mail::send('vendor.emailTrakingViews.emails.mensaje', $data, function($message) use ($people, $subject , $sender_email,$sender_name){
                        $message->to($people->email, $people->first_name)
                                ->subject($subject);
                        $message->from($sender_email,$sender_name);
                        $message->getHeaders()->addTextHeader('X-No-Track',str_random(10));
                    });
```

**Comment by jdavidbakr** [comment]
Since you're not letting Laravel initialize the swift mailer it's not registering the plugin.  Might try this to see if it gets the plugin registered (look at the package source for reference of how it registers the plugin with the Laravel swift mailer):

```
$temp_sender->registerPlugin(new MailTracker());
```

**Comment by stacybot123** [comment]
Thanks, I tried registering the plugin , it still not working. I will look into it , will post if I get something. Thank you for creating this the awesome sdk!
