### ISSUE TITLE
How to use this package with Gmail API

### ISSUE THREAD

**Issue by annadow75** [jdavidbakr/mail-tracker#60]
Hi,

I am trying to use the package with Gmail API, not sure if this will support that or not. Can you guide me  the steps I should take to make the view and then use the gmail api to send the email

**Comment by jdavidbakr** [comment]
This will only support using the package via the Laravel-native swift mailer.  I don't know anything about the Gmail API, if it is a mail driver in Laravel then it should work, but if not you might be able to get it to work by copying and/or extending the classes.
