### ISSUE TITLE
Add option to not save content of some email

### ISSUE THREAD

**Issue by Scuissiatto** [jdavidbakr/mail-tracker#62]
Hi there,

First, thanks for sharing this awesome work.

In my case we send a ton of mails and although we want to keep track of it, our DB size is growing really fast, and the content is not that important.

Do you think is possible to set per email basis if we want to save the content?

Perhaps with another Header setting?

**Comment by jdavidbakr** [comment]
This already exists - just add an `X-No-Track` to your email headers with any string as the value.  See the Readme for additional info.

**Comment by Scuissiatto** [comment]
Yeah. This works fine if I don't want to track the whole mail.

What I'm asking/suggesting is to track the mail without saving it's content in order to save some DB space.
