### ISSUE TITLE
Better to Track only allowed mails?

### ISSUE THREAD

**Issue by LonnyX** [jdavidbakr/mail-tracker#63]
Hello,

First, I would like to thank you for this packages, it's works like a charm.
I wonder if it's better to Track only allowed emails and not Track all except specified...

Why? Because sometime mails are sent from a Package and you don't have to ability to add the tag X-No-Track without forking the package. The same things occurs with built-in Laravel email (Password reset, email confirmation ...)

It's a pretty easy fix, I can make a PR if you want

**Comment by jdavidbakr** [comment]
Sure, feel free to make a PR.  As long as the default continues to behave as it currently does.  Also be sure to update the readme in your pull request.

**Comment by LonnyX** [comment]
Of course the default will not continues to behaves as it currently does. This is a breaking change because it'll require that users define explicitly Emails to be tracked

**Comment by LonnyX** [comment]
I understand your point. I thought that's more convenable that we we track only what we want to be tracked. (instead of exclude what we don't want)
But of course you decide 😄

**Comment by jdavidbakr** [comment]
I have no problem with it being a configurable option, though.

**Comment by LonnyX** [comment]
Oki, I'll try to create a PR this weekend 👍 
Do you have an idea if we can add a header from Notification without creating a Listener?

**Comment by jdavidbakr** [comment]
I haven't looked to see how to add headers to emails since Laravel moved to the `Mailable`/`Notifications` away from the `Mail` facade.
