### ISSUE TITLE
Track location

### ISSUE THREAD

**Issue by ahmedalmulki** [jdavidbakr/mail-tracker#64]
Hi, thanks for creating like this library it's easy and worked without any error, but I am searching how can I track the location of recipients IP or Country,
is that possible with your library?
Thanks

**Comment by jdavidbakr** [comment]
You could probably write a hook into the ViewEmailEvent, you should have access to the request() object that performed the pingback which should contain the IP address.  Then you could use a third party lookup to get the country.

**Comment by DeveloperOnCall** [comment]
This would be a simple addition - I'll use a crude, untested example here.

**1.)** Add a method to a related class (not recommended to add it to the Listener better to call it from the EmailViewed listener you created from the readme doc).


`

    function trackLocation() {
        if(!empty($_SERVER['HTTP_CLIENT_IP'])){
            $ip = $_SERVER['HTTP_CLIENT_IP'];
        } elseif(!empty($_SERVER['HTTP_X_FORWARDED_FOR'])){
            $ip = $_SERVER['HTTP_X_FORWARDED_FOR'];
        } else {
            $ip = $_SERVER['REMOTE_ADDR'];
        }
        if ( $ip ) {
            // Get geoip location
            $ch =  curl_init('http://api.ipapi.com/'.$ip.'?access_key=YOUR_API_KEY'); // API KEY = Create Free account here ==> https://ipapi.com
            curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
            curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, 0);
            curl_setopt($ch, CURLOPT_HTTPAUTH, CURLAUTH_BASIC);
            curl_setopt($ch, CURLOPT_CONNECTTIMEOUT, 5);
            curl_setopt($ch, CURLOPT_ENCODING,  '');
            curl_setopt($ch, CURLOPT_IPRESOLVE, CURL_IPRESOLVE_V4 );
            curl_setopt($ch, CURLOPT_TIMEOUT, 3);
            curl_setopt($ch, CURLOPT_HTTPHEADER, array('Accept: application/json'));
            $s = json_decode(curl_exec($ch), true);
            
            if (is_array($s)) {
                if(array_key_exists('type', $s) && $s['type'] == "error"){
                    //error_log('Error : Fail to get Geo location : '.$s['msg']); // if you want to log the error uncomment this line
                }
                else
                    return $s;
            }
        }

        return false;
    }`

**2.)** Add a few fields to the tracking tables. These are basic info but take a look at the JSON returned by the IP/Geo service and choose additional fields as desired. 

`

    Schema::table('sent_emails', function(Blueprint $table) {
                $table->string('country_code')->nullable();
                 $table->string('country_name')->nullable();
                 $table->string('latitude')->nullable();
                $table->string('longitude')->nullable();
            }); 
            
        `

**3.)** Update the database (I'd create your own Model ie: App/Models/SentEmails) with the results contained in the $s returned array.

Kind of a crude explanation and how-to, but thought I'd offer my 2-cents.

:)

**Comment by jdavidbakr** [comment]
I'm going to close this as this should be able to be accomplished in an event listener and I don't think I want to include this in the package.  Thanks, @DeveloperOnCall for the reference to the Geolocation API.

**Comment by tormjens** [comment]
@jdavidbakr While this was working prior to https://github.com/jdavidbakr/mail-tracker/commit/2b039c30bb643e608040ada882fb8cb2aeea58ca it no longer seems to work and I can't see a way around that with the way it is implemented. In a queue, at least on that is not synchroneus, we don't really have the "real" request object at hand. This means that `request()->ip()` would return `127.0.0.1` or something similar. Before I attempt a PR here, would you be happy to accept one either: a) passed an array of useful parameters from the request to the job making it possible to "hydrate" the request somewhat sane, or b) made it possible to configure whether you want the event to be queued or not?

**Comment by jdavidbakr** [comment]
That's an interesting use case.  I've created a new issue here: https://github.com/jdavidbakr/mail-tracker/issues/151
