### ISSUE TITLE
Not working in lumen

### ISSUE THREAD

**Issue by manavchawla2012** [jdavidbakr/mail-tracker#66]
I made it work in laravel but when I tried in my lumen project it showed this issue when I tried registering the events.

> PHP Fatal error:  Call to undefined method Laravel\Lumen\Application::name() in D:\evibe\apis\vendor\jdavidbakr\mail-tracker\src\MailTrackerServiceProvider.php on line 116

>Fatal error: Call to undefined method Laravel\Lumen\Application::name() in D:\evibe\apis\vendor\jdavidbakr\mail-tracker\src\MailTrackerServiceProvider.php on line 116

**Comment by jdavidbakr** [comment]
I never use Lumen, the Lumen instructions were done by a contributor.  If someone wants to submit a pull request to fix this, I'm all for it; otherwise, I may just remove Lumen support from the Readme.

**Comment by jdavidbakr** [comment]
Officially removing Lumen support: https://github.com/jdavidbakr/mail-tracker/commit/59630b8aa82e2d43056168d2945e344af4103cf0
