### ISSUE TITLE
AWS SNS Subscription

### ISSUE THREAD

**Issue by DeveloperOnCall** [jdavidbakr/mail-tracker#67]
When subscribing to the SNS Topic the subscription remains in the 'PendingConfirmation' state. 

Is there some further action/change required to confirm the subscription?

I created the subscription using the endpoint as described in the readme getting the endpoint URL from the /email-manager page view. I have also set the 'sns-topic' in the mail-tracker.php config.

When that URL is opened manually it shows 'MethodNotAllowedHttpException' so I assume its a POST route and the route is working properly.

**Comment by DeveloperOnCall** [comment]
Thanks @jdavidbakr 

Using the SNS Endpoint from /email-manager view I create a subscription under the ARNTopic
That immediately adds the Pending under Subscription ID

I tried the 'Confirm Subscription' button and again pasted the SNS Endpoint.

I added logging to two places - SNSController->callback and to SNSController->confirm_subscription

Nothing added to the log at all.  

Can you recommend my next step?

Thanks again, 
Daniel

**Comment by jdavidbakr** [comment]
You don't need to confirm the subscription, what happens when you create a subscription is that SNS immediately sends a request to the endpoint, and the mail tracker code will handle the confirmation when it gets the request.  If the subscription is not immediately confirmed, there is either an issue with SNS being able to contact the endpoint, or the endpoint from being able to post back to SNS.  This is most likely some setting on your server, which is why I would suggest looking in the logs to make sure there are no errors.

**Comment by jdavidbakr** [comment]
The only time I've had that happen is if I had accidentally set the protocol to http when it should have been https (or vice versa), or if I had the server behind a firewall that wasn't publicly open.  I am assuming this is on a public server?

**Comment by DeveloperOnCall** [comment]
Yes - no Firewall that would block public calls.

**Comment by DeveloperOnCall** [comment]
I am afraid this is an AWS issue (might be that the EC2 instance is in a different region than the Topic, SES Mailer etc.

No use tying you up with this, so I'll just close it off.

Thanks again.
D

**Comment by mitjarobic** [comment]
This does the trick...
```
/**
* The URIs that should be excluded from CSRF verification.
*
* @var array
*/
protected $except = [
   '/email/sns'
];
```

**Comment by connecteev** [comment]
@mitjarobic @DeveloperOnCall having this very same issue - spent hours debugging. Were you able to confirm the subscription? THis is what I see: https://prnt.sc/pqhwzc
I did what @mitjarobic suggested in  VerifyCsrfToken.php - any thoughts on what I need to do next?

**Comment by jdavidbakr** [comment]
I actually typically put the callback in the `api` group to avoid the CSRF issue.  (I probably should make that the default in the published config)

**Comment by connecteev** [comment]
@jdavidbakr thank you, would you mind showing how you did that?
I'm currently stuck on this (detailed everything in #91 and would appreciate your input so I can get  unblocked!

**Comment by jdavidbakr** [comment]
Just be sure you publish the config file and in there is the settings for the callback routes.  

```
    /**
     * Where should the pingback URL route be?
     */
    'route' => [
        'prefix' => 'email',
        'middleware' => ['web'],
    ],
```

**Comment by connecteev** [comment]
@jdavidbakr I have published my config and those are the exact (default) settings I have.

This is what I did to create my SNS subscription:
https://prnt.sc/pqh45i
and after adding the subscription I see something like this: https://prnt.sc/pqhwzc (The Subscription in SNS shows "Pending confirmation")

The SNS endpoint I added is accessible publicly (changed the URL to make sure my computer doesn't get hacked): http://mysite-6hd2.localhost.run/email/sns

How can I get this out of "Pending confirmation" state, how can I test the Delivery / Bounce / Complaint notifications? The SNS docs said something like, if it's not confirmed, no notifications will be sent.

**Comment by connecteev** [comment]
@jdavidbakr Btw if we can figure this out I would not only be grateful, but I'll also submit a PR to the readme to make it easier for others in the future.

**Comment by jdavidbakr** [comment]
When you create the subscription, immediately AWS sends a request to the URL you entered.  If the site doesn't immediately respond, then your endpoint is not accessible to AWS.  Can you SSH into an external terminal and just curl your URL to make sure that it is publicly accessible?  I don't know anything about localhost.run but if you are logging your requests you should at least see the SNS requests arriving.  If you don't, it's not an issue with the package, it's an issue with AWS being able to access your server.

**Comment by connecteev** [comment]
I see. Well, it is publicly accessible..try going to https://kunalpunjabi-yg25.localhost.run

I also verfified that I can ping it from outside my network, after ssh'ing to my external linode:

```
ping https://kunalpunjabi-yg25.localhost.run
PING https\058\047\047kunalpunjabi-yg25.localhost.run (35.193.161.204) 56(84) bytes of data.
64 bytes from 204.161.193.35.bc.googleusercontent.com (35.193.161.204): icmp_seq=1 ttl=47 time=36.8 ms
64 bytes from 204.161.193.35.bc.googleusercontent.com (35.193.161.204): icmp_seq=2 ttl=47 time=36.8 ms
64 bytes from 204.161.193.35.bc.googleusercontent.com (35.193.161.204): icmp_seq=3 ttl=47 time=36.7 ms
64 bytes from 204.161.193.35.bc.googleusercontent.com (35.193.161.204): icmp_seq=4 ttl=47 time=36.8 ms
64 bytes from 204.161.193.35.bc.googleusercontent.com (35.193.161.204): icmp_seq=5 ttl=47 time=36.9 ms
64 bytes from 204.161.193.35.bc.googleusercontent.com (35.193.161.204): icmp_seq=6 ttl=47 time=36.8 ms
```

I am going to try to log SNS Delivery events (will try extending your package to fire that event, I hope it works and will keep you posted). If you have pointers to help that would be great too.

**Comment by jdavidbakr** [comment]
Just watch your access log?  I can't go to that url, btw.

```
$ curl https://kunalpunjabi-yg25.localhost.run/
curl: (35) LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to kunalpunjabi-yg25.localhost.run:443 
```

**Comment by connecteev** [comment]
Yes, sorry my process died...but it was accessible for a while. How are you testing this from localhost? What do you use? I'm trying to run the package's unit tests to debug this.

**Comment by connecteev** [comment]
New URL: https://af84a2ab.ngrok.io

**Comment by jdavidbakr** [comment]
With that I'm getting the expected response when I curl it:

```
$ curl -X POST https://af84a2ab.ngrok.io/email/sns -H "Accept: application/json"
{
    "message": "SNS message type header not provided.",
    "exception": "RuntimeException",
    "file": "/Users/kunalpunjabi/Code/EXPLORATIONS/EMAILS_QUEUES_CACHING_REDIS/jdavidbakr_mail_tracker/vendor/aws/aws-php-sns-mess
...
```

You put https://af84a2ab.ngrok.io/email/sns in SNS and it didn't verify it?

**Comment by connecteev** [comment]
Progress....the subscription is confirmed / verified now. 
https://prnt.sc/pqss4q

Previously I was using localhost.run to create a public url - though the URL was publicly accessible the SNS subscription just flat-out went into pending state and I had no way to confirm it (the remaining 3 subscriptions you can see at the screenshot above).

Now I'm using ngrok - with ngrok things are looking better and it instantly confirmed the SNS subscription. Settings: https://prnt.sc/pqspoc

My next step is to see if I can get a notification from SNS. What is the easiest way to verify that delivery / bounce / complaints are working? Thanks for your help!

**Comment by jdavidbakr** [comment]
Look at the SES documentation - there are addresses you can send to to trigger the different responses.

**Comment by connecteev** [comment]
Thanks....Is there a link to this, because I can't seem to find it in the SES documentation?
Also, how can I trigger the unit tests that come with this package?

**Comment by jdavidbakr** [comment]
https://docs.aws.amazon.com/ses/latest/DeveloperGuide/mailbox-simulator.html

You can run the tests within the package with the standard `vendor/bin/phpunit`

**Comment by connecteev** [comment]
Thanks....I tried sending to those email addresses:
```
success@simulator.amazonses.com
bounce@simulator.amazonses.com
complaint@simulator.amazonses.com
```

Email forwarding notifications: I am getting bounce / complaint notifications, but not delivery notifications. That aside, in all cases (bounce / complaint / delivery), no SNS HTTP(S) POST notifications are received at https://af84a2ab.ngrok.io/email/sns 
My settings: https://prnt.sc/pquysj

The way I know this is I have a very simple insert in each of my listeners, and it never gets called:

```
    public function handle(PermanentBouncedMessageEvent $event)
    {
        // Access the email address using $event->email_address...
        \DB::table('sns_logs')->insert(
            ['raw_message' => json_encode($event)]
        );
    }
```

Running the unit tests gives me this error:
```
$ pwd
/Users/kunalpunjabi/Code/EXPLORATIONS/EMAILS_QUEUES_CACHING_REDIS/jdavidbakr_mail_tracker
OneStepAtATime:jdavidbakr_mail_tracker kunalpunjabi$ 
OneStepAtATime:jdavidbakr_mail_tracker kunalpunjabi$ vendor/bin/phpunit vendor/jdavidbakr/mail-tracker/tests/
PHP Fatal error:  Uncaught Error: Class 'Orchestra\Testbench\Exceptions\Handler' not found in /Users/kunalpunjabi/Code/EXPLORATIONS/EMAILS_QUEUES_CACHING_REDIS/jdavidbakr_mail_tracker/vendor/jdavidbakr/mail-tracker/tests/MailTrackerTest.php:12
Stack trace:
#0 /Users/kunalpunjabi/Code/EXPLORATIONS/EMAILS_QUEUES_CACHING_REDIS/jdavidbakr_mail_tracker/vendor/phpunit/phpunit/src/Util/FileLoader.php(59): include_once()
#1 /Users/kunalpunjabi/Code/EXPLORATIONS/EMAILS_QUEUES_CACHING_REDIS/jdavidbakr_mail_tracker/vendor/phpunit/phpunit/src/Util/FileLoader.php(47): PHPUnit\Util\FileLoader::load('/Users/kunalpun...')
#2 /Users/kunalpunjabi/Code/EXPLORATIONS/EMAILS_QUEUES_CACHING_REDIS/jdavidbakr_mail_tracker/vendor/phpunit/phpunit/src/Framework/TestSuite.php(346): PHPUnit\Util\FileLoader::checkAndLoad('/Users/kunalpun...')
#3 /Users/kunalpunjabi/Code/EXPLORATIONS/EMAILS_QUEUES_CACHING_REDIS/jdavidbakr_mail_tracker/vendor/phpunit/phpunit/src/Framework/TestSuite.php(438): PHPUnit\Framework\TestSuite->addTestFile('/Users/kunalpun...')
#4 /U in /Users/kunalpunjabi/Code/EXPLORATIONS/EMAILS_QUEUES_CACHING_REDIS/jdavidbakr_mail_tracker/vendor/jdavidbakr/mail-tracker/tests/MailTrackerTest.php on line 12

Fatal error: Uncaught Error: Class 'Orchestra\Testbench\Exceptions\Handler' not found in /Users/kunalpunjabi/Code/EXPLORATIONS/EMAILS_QUEUES_CACHING_REDIS/jdavidbakr_mail_tracker/vendor/jdavidbakr/mail-tracker/tests/MailTrackerTest.php:12
Stack trace:
#0 /Users/kunalpunjabi/Code/EXPLORATIONS/EMAILS_QUEUES_CACHING_REDIS/jdavidbakr_mail_tracker/vendor/phpunit/phpunit/src/Util/FileLoader.php(59): include_once()
#1 /Users/kunalpunjabi/Code/EXPLORATIONS/EMAILS_QUEUES_CACHING_REDIS/jdavidbakr_mail_tracker/vendor/phpunit/phpunit/src/Util/FileLoader.php(47): PHPUnit\Util\FileLoader::load('/Users/kunalpun...')
#2 /Users/kunalpunjabi/Code/EXPLORATIONS/EMAILS_QUEUES_CACHING_REDIS/jdavidbakr_mail_tracker/vendor/phpunit/phpunit/src/Framework/TestSuite.php(346): PHPUnit\Util\FileLoader::checkAndLoad('/Users/kunalpun...')
#3 /Users/kunalpunjabi/Code/EXPLORATIONS/EMAILS_QUEUES_CACHING_REDIS/jdavidbakr_mail_tracker/vendor/phpunit/phpunit/src/Framework/TestSuite.php(438): PHPUnit\Framework\TestSuite->addTestFile('/Users/kunalpun...')
#4 /U in /Users/kunalpunjabi/Code/EXPLORATIONS/EMAILS_QUEUES_CACHING_REDIS/jdavidbakr_mail_tracker/vendor/jdavidbakr/mail-tracker/tests/MailTrackerTest.php on line 12
```

**Comment by connecteev** [comment]
I then enabled Cloudwatch Logs for SMS messages:
https://docs.aws.amazon.com/sns/latest/dg/sms_stats_cloudwatch.html?shortFooter=true#sns-viewing-cloudwatch-logs
I found documentation pointing me to cloudwatch:

This is what I did next:
```
Sent email From: support@keenbrain.com To: complaint@simulator.amazonses.com
Received: Complaint email notification received (at support@keenbrain.com )
```


This is what the cloudwatch logs show:
Screenshots:
prnt.sc/prdufv
prnt.sc/prdukf

```
{
    "notification": {
        "messageMD5Sum": "8f10e089c532ef6f078e9860cd028d24",
        "messageId": "70c867fc-4d68-5dc4-adae-31cabe42a76f",
        "topicArn": "arn:aws:sns:us-west-2:753513409872:KeenBrain_Amazon_SNS_for_SES_Emails_Topic",
        "timestamp": "2019-11-02 02:58:50.382"
    },
    "delivery": {
        "deliveryId": "88181b7b-6a95-5980-8fa6-4d4d990f3bab",
        "destination": "https://1133c091.ngrok.io/email/sns",
        "providerResponse": "Internal Server Error",
        "dwellTimeMs": 112754,
        "attempts": 3,
        "statusCode": 500
    },
    "status": "FAILURE"
}
```

So, looks like some sort of bug on the application side, possibly in the package itself, since I haven't changed it from the default.
