### ISSUE TITLE
Tracking code at the top?

### ISSUE THREAD

**Issue by KriiV** [jdavidbakr/mail-tracker#7]
I've noticed that the tracking code is shown as the excerpt text when receiving an email on iPhones. Is there a way to change the place of the tracking text so that the subtitle of the email isn' the tracking code?

Thanks

**Comment by jdavidbakr** [comment]
Does your html have a <body> tag in it?  I haven't noticed this happening (I do have an iPhone) but there is a separate injection command depending on whether the html has a <body> element or not, and all of my emails have a <body> tag.  I'd be interested to know if you experience this with and/or without your html having <body> elements.

**Comment by KriiV** [comment]
There is no `<html>` tag if that's what you mean? I do use `<br />` though.

**Comment by jdavidbakr** [comment]
Ok, I wonder if the iPhone handles it differently if it's not in a <body> tag.  I've pushed the code to the end in this case in 2.1.1
