### ISSUE TITLE
Emoji in emails cause MySQL exceptions

### ISSUE THREAD

**Issue by mr-mmmmore** [jdavidbakr/mail-tracker#72]
Unless the database and connections are configured to use utf8mb4, emojis can't be stored in the 'content' column. It causes an exception from MySQL.

To solve this, one should change the db configuration to use utf8mb4, but I find it is too constraining to impose this only to avoid a potential problem in email tracking.

So I have added a fix that replaces emojis from the content just before it is inserted  into the database. I can submit a PR if you want.

**Comment by jdavidbakr** [comment]
I'm going to leave this as it is, because newer versions of Laravel default to utf8mb4.  Feel free to write a model observer in your application to specifically address this issue.
