### ISSUE TITLE
Passing a bad hash to MailTrackerController::getL causes error 500

### ISSUE THREAD

**Issue by mr-mmmmore** [jdavidbakr/mail-tracker#73]
I have found some HTTP 500 errors in the log of my server after deploying the package, and it appears those errors come from the `/emails/l` route when bad parameters are passed. One specific request has caused these errors:

`/emails/l/cJJ3bIH3Nm0afLA8Lceve0fbJZ0me72lc0JdbeDfUACaam4lFUOibSgjX0wlBXFcbs8dbQDsdi4maG9gcL4nbKEcfWhjfKSm/FGnf0pISQBEartpDJ56bBC7alRA4PahR`

This request is weird because no email in the database has the hash passed at the end of the url. Looks like some kind of attack.

Since no email sent is found, the controllers' `getL` method runs the `redirect($url)` at the end. But the $url parameter passed through the url once decoded is not an url, it's this exact string:

`b"pÆwlü¸6m\x1A|░<-Ã»{G█%Ø&{¢ÑsB]mÓ▀P\x00Üjn%\x15Cóm(#_L%\x05q\n¤\x1Dm\x00ýv.&ho`p¥'lí\x1C}hc|ñª"`

It seems forged...

This string is then used directly in the line `redirect($url)` at the end of the method! This causes the 500 error.

So, passing a random string shouldn't cause the server to fail. So I've added this piece of code at the beginning of the method so the redirection is made to the domain's root if the redirection url is not valid:

```
public function getL($url, $hash)
{
    $url = base64_decode(str_replace("$", "/", $url));

    // code added:
    if (filter_var($url, FILTER_VALIDATE_URL) === false) {
        Log::warning('MailTrackerController::getL - the url to redirect to is not valid', ['currentUrl' => request()->url()]);
        return redirect('/');
    }

    // rest of the function...
```
I can submit a PR if you want.

**Comment by jdavidbakr** [comment]
Added a check and appropriate exception: https://github.com/jdavidbakr/mail-tracker/commit/44b82489257fdb432e5a68e7876e467d19b58637
