### ISSUE TITLE
Not track is email open when using queue

### ISSUE THREAD

**Issue by bogi872000** [jdavidbakr/mail-tracker#74]
I have a problem its works before I implement email job, does anyone face this problem?

**Comment by jdavidbakr** [comment]
All my mail goes out via the queue, so I don't know of any issues.  Did you just install it, and if so, did you restart your queue workers?

**Comment by bogi872000** [comment]
Hi thx for response,

I think i found the problem.

Its inject pixel but when mail send from queue its not accessible return 404.

> http://localhost/email/t/KnHaCX1VKtPtVsct5cEotMUBKijm2s92 - 404

and when I send email without queue has status 200 its found link in that moment  and email can be tracked

> http://payroll.test/email/t/rWzjG88cbw08DRVBzJow8dM9NHuuAoa8 - 200

Any idea did I miss something

**Comment by bogi872000** [comment]
Problem solved if using queue must specify APP_URL in .env file, and all works

**Comment by jdavidbakr** [comment]
Yes, queued mail must have the APP_URL set correctly.
