### ISSUE TITLE
No Track causing issue with SES

### ISSUE THREAD

**Issue by mdafzal** [jdavidbakr/mail-tracker#75]
First, many many thanks for this awesome package!

I am using Amazon SES for mails and I don't want certain mails to be tracked. For this purpose, I have added header as mentioned in docs.
$message->getHeaders()->addTextHeader('X-No-Track', str_random(10));

But this is creating error:
 Uncaught Error: Call to a member function getFieldBody() on null in /home/vagrant/code/vendor/jdavidbakr/mail-tracker/src/MailTracker.php:41

**Comment by mdafzal** [comment]
Any one ?

**Comment by jdavidbakr** [comment]
Fixed https://github.com/jdavidbakr/mail-tracker/releases/tag/2.1.22
