### ISSUE TITLE
Redirect urls stored as regular urls in log

### ISSUE THREAD

**Issue by robov** [jdavidbakr/mail-tracker#76]
Awesome package.... really love it.
The log contains the non-redirected urls, I am not sure if this is supposed to be this way.

I wonder what happens when I use the data in the log to RE-send the message in case the user deleted it...
is the redirect link restored ?

**Comment by jdavidbakr** [comment]
If you do it within Laravel, it should inject the tracking code and rewrite the URLs just like it was the original email.  It would, of course, be logged as a new email.
