### ISSUE TITLE
Not getting email open count when using mailgun

### ISSUE THREAD

**Issue by ancyabraham936** [jdavidbakr/mail-tracker#77]
I am using laravel version 5.6 and mailgun as the email client. Project is running on localhost. The problem is i am not getting the email open count but i get link click count without any issue. Can you help me with a solution?

**Comment by jdavidbakr** [comment]
Look at the closed issues about local environments not working and make sure that this doesn't fall into one of those categories (i.e. gmail will not work in testing if you have a localhost setup).  If those don't apply, open a new issue with details about what steps you tried from those other tickets.

**Comment by ancyabraham936** [comment]
Its working now. I just changed the localhost setup to live. Thanks for your time
