### ISSUE TITLE
Link tracker to model

### ISSUE THREAD

**Issue by depsimon** [jdavidbakr/mail-tracker#8]
Is there a way to link a tracker to a model ?

My application sends emails automatically based on actions such as "OrderShipped" and I'd like to link the tracker to the specific Order so that I can display all emails linked to an Order.

I see there's a `meta` column in the `sent_emails` table, how would I edit this according to the notification ?

**Comment by jdavidbakr** [comment]
I added the meta field for this purpose, but haven't built anything that puts data in there yet.  I haven't figured out a good way to pass metadata to the mailer without extending the Swift mailer - which I may end up doing, but would like to avoid.

**Comment by Narayan-codelee** [comment]
I have different table messages for sending email having subject, body and email. How can i map my (own message-id) with ses message id so that i can find which email has been sent?

**Comment by jdavidbakr** [comment]
I have an idea that might work.  If you compose your message with a custom header to identify the primary key of a table, you could add an event listener for jdavidbakr\MailTracker\Events\EmailSentEvent and extract it from the message.

The handler for jdavidbakr\MailTracker\Events\EmailSentEvent receives a jdavidbakr\MailTracker\Model\SentEmail object - @Narayan-codelee, if you are using version 2.1 this has an attribute message_id that is the Amazon SES message id if you are using SES - and in this event you could extract the custom header from the headers attribute and then do additional processing/linking/store data in the meta attribute at that point.

**Comment by jdavidbakr** [comment]
I have added an accessor to the headers in the SentEmail model, and instructions in the README about how to pass data to your event listeners so that you can do additional model processing.
