### ISSUE TITLE
Integration with SendGrid?

### ISSUE THREAD

**Issue by xlcrr** [jdavidbakr/mail-tracker#80]
Hi guys,

Plugin works great with Mailgun, but it doesn't pick up on emails being sent out with sendgrid.

Current project I am working on has extracted a lot of code into our controllers to achieve tracking but it's messy.

How can I achieve link tracking emails going through sendgrid without extracting the code into our controllers? V7.3

Many thanks

**Comment by xlcrr** [comment]
Hi again,

I was able the figure how to track emails manually but not through the use of the plugin

For anyone interested, we simply created links with the following syntax

```
$hash = Str::random(32);

$link = 'https://mysite.com/route/' . $token

$trackedLink = 'https://mysite.com/email/l/' . base64_encode($link) . '/' . $hash;
```

then the plugin will automatically pick up the link when you visit the route

**Comment by bretto36** [comment]
We use SendGrid and the tracking works fine. Have you got the config options enabled 
`'track-links' => true,`
