### ISSUE TITLE
Tracking opens and disable link tracking

### ISSUE THREAD

**Issue by stacybot123** [jdavidbakr/mail-tracker#82]
Hi,

is there a way I can only track email opens and disable link tracking on an email?

on adding below it stops tracking open also
```
->getHeaders()->addTextHeader('X-No-Track',Str::random(10));
```
and on adding below it starts tracking links also

```
->getHeaders()->addTextHeader('SENT-EMAIL', $my_identifier);
```

Thanks

**Comment by jdavidbakr** [comment]
See the config for the setting to disable link tracking.
