### ISSUE TITLE
Laravel 6 support

### ISSUE THREAD

**Issue by Christophvh** [jdavidbakr/mail-tracker#84]
This package currently does not support Laravel 6

**Comment by jdavidbakr** [comment]
Dependent on this package https://github.com/aws/aws-sdk-php-laravel/issues/168

**Comment by drbyte** [comment]
@jdavidbakr Are you sure the `aws/aws-sdk-php-laravel` dependency is actually needed?
It's not used/referenced anywhere in the code, and all the mail-tracker tests pass without it.

It was added back in https://github.com/jdavidbakr/mail-tracker/pull/34 but I'm not seeing where anything it provides is actually used.

**Comment by jdavidbakr** [comment]
@drbyte it looks like you are right.  Releasing 2.1.26 without that dependency.
