### ISSUE TITLE
telephone urls, url validation doesnt work.

### ISSUE THREAD

**Issue by ideea** [jdavidbakr/mail-tracker#86]
![image](https://user-images.githubusercontent.com/318955/64949853-cbea7880-d882-11e9-8c30-9e3444ea2092.png)

clicking phone urls doesnt work. url filtering should be updated/fixed.

**Comment by jdavidbakr** [comment]
What version are you experiencing this in?  I believe emails sent via 2.2 will not experience this behavior.

**Comment by ideea** [comment]
Yup. i was using 2.1 version. 2.2 helped. thanks!
