### ISSUE TITLE
Storing metadata in sent_emails

### ISSUE THREAD

**Issue by connecteev** [jdavidbakr/mail-tracker#90]
Great package! Works really nicely, and it also has a neat Admin interface. I have 2 questions, putting them into separate issues for easy tracking.

Here's how I'm sending emails using Mailables - this works like a charm, both with Mailtrap and with SES.

```
Route::get('/', function () {
    Mail::to("recipient@gmail.com")
    ->queue(new App\Mail\UserRegistered())
    ;
});
```

In my UserRegistered Mailable:
```
    public function build()
    {
        return $this
            ->from('myemail@gmail.com')
            ->subject('This is a great subject line man')
            ->view('emails.user_registered')
            // ->withSwiftMessage(function ($message) {
            //     $message->getHeaders()
            //             ->addTextHeader('Custom-Header', 'HeaderValue');
            // })
            ;
    }

```

My problem is, I am looking to store some additional metadata (in my case, the user ID that the email was sent to) in the meta field of the sent_emails table. Is there an example of how I can do that? Thanks in advance for any help here.

**Comment by connecteev** [comment]
@jdavidbakr 
I got it working by passing data into the email header, and then retrieving it in the event listener, as per your comment [here](https://github.com/jdavidbakr/mail-tracker/issues/8).
I'm not sure if this is the most efficient way (passing the data into the email header), but it seems to work. I'd be interested in your thoughts if there's a better way to do it, if there is one.

**Comment by jdavidbakr** [comment]
@connecteev If you can think of a more efficient way, I'm all ears!  That was the only way I could come up with without overly complicating the process.

**Comment by connecteev** [comment]
@jdavidbakr I may not have fully thought things through here, but when this call is made:
```
Mail::to("recipient@gmail.com")
    ->queue(new App\Mail\UserRegistered())
    ;
```
how does your package intercept and store a record in sent_emails? Would it be possible to store meta in build(), before the return statement below?

```
    public function build()
    {
        return $this
            ->from('myemail@gmail.com')
            ->subject('This is a great subject line man')
            ->view('emails.user_registered')
            // ->withSwiftMessage(function ($message) {
            //     $message->getHeaders()
            //             ->addTextHeader('Custom-Header', 'HeaderValue');
            // })
            ;
    }
```

Maybe there's a way to pass the data to Swift_Events_SendEvent $event here:
```
public function beforeSendPerformed(\Swift_Events_SendEvent $event)
```
Again, I dont understand how it all works in the background...so this may or may not be even possible.
