### ISSUE TITLE
Uninstall is not working

### ISSUE THREAD

**Issue by macroantu** [jdavidbakr/mail-tracker#93]
I have tried to uninstall this package and successfully uninstalled but whenever i send mail using queue system i can see whatever link i have used inside my Message Body that is encrypted which is coming from MailTrackerController.php how can i solve this issue.  I tried using 2.1 and 2.0 version as i am a laravel 5.4 user.

**Comment by jdavidbakr** [comment]
If you have uninstalled it then MailTrackerController.php should no longer be in your site ... so I'm not sure how it would be doing anything if it's not installed.  Did you restart your queue workers after you uninstalled it?

**Comment by macroantu** [comment]
> If you have uninstalled it then MailTrackerController.php should no longer be in your site ... so I'm not sure how it would be doing anything if it's not installed. Did you restart your queue workers after you uninstalled it?

I have restarted my queue work , i am removed full vendor folder and install composer again. cleared config, cache, route . but same. when i am sending mail using driver= 'sync' it is all good but whenever i use driver = database then i can see whatever link i use inside my message body it get encrypted  like this 
http://mywebsite.com/email/l/IGh0dHBzOi8vbGltaXRsZXNzZWJvb2tzLmNvbT9kbT1lYiZhdWRpZW5jZT03OTQ4ODMyNjQ1NjQ5MF9hbnR1cmomcGVvcGxlPWFudHVyakBnbWFpbC5jb20mY2FtcD0xJmN1c3RfY2FtcD0xMg==/lILtlHLshOZufkpz6oksVAOeKrG4xMV3

**Comment by jdavidbakr** [comment]
The only way that makes sense is if you still have a queue worker active from before you uninstalled it.  If you stop the queue workers does the email still get sent?

**Comment by macroantu** [comment]
i am using supervisor  to run queue in my server, i can't stop this or restart this queue work using php artisan command i am getting this error, file_put_contents(/var/www/html/website/storage/framework/cache/data/ee/2f/ee2  
  f842aa7bb1f53edf3a2ed2c09a1807ffa6c90): failed to open stream: No such file  
   or directory

**Comment by jdavidbakr** [comment]
This sounds like an issue outside of this package, as the reason you are still getting links marked is because your queue worker still has the previous code.

**Comment by macroantu** [comment]
thanks for the help you were right it was all about previous thing was still there. I have fixed the problem and re-queued  and now all is working. Thanks a lot.
