### ISSUE TITLE
Is it possible to get the request object on the Events

### ISSUE THREAD

**Issue by abishekrsrikaanth** [jdavidbakr/mail-tracker#94]
Is it possible to get the request object when the events are triggered? I would like generate some analytics using the data on the request object. If not, do you have any other alternatives?

**Comment by abishekrsrikaanth** [comment]
@jdavidbakr any suggestions?

**Comment by jdavidbakr** [comment]
This would be a breaking change in the current version but there is a pull request that I believe will do this; I just haven't had the margin to review it and merge it yet.

**Comment by abishekrsrikaanth** [comment]
Thanks for the response. I did look into all the current open PR's and couldn't find one that already has this. I was think more in terms of passing the request object as a parameter to the Event Class https://github.com/jdavidbakr/mail-tracker/blob/master/src/MailTrackerController.php#L35 and https://github.com/jdavidbakr/mail-tracker/blob/master/src/MailTrackerController.php#L75, so they can be accessed by the listeners through a getter from the eventclass object. I assume this wouldn't break anything.

**Comment by jdavidbakr** [comment]
Can you not just use the request() helper function?

**Comment by abishekrsrikaanth** [comment]
Thanks
