### ISSUE TITLE
Remove Laravel Framework dependency

### ISSUE THREAD

**Issue by abishekrsrikaanth** [jdavidbakr/mail-tracker#95]
Currently this package has a dependency set to Laravel Framework https://github.com/jdavidbakr/mail-tracker/blob/master/composer.json#L19. Can this be removed and only the required laravel packages be included into it. Installing this on a Lumen app, adds the Laravel Framework to the vendor directory and creates conflicts.

**Comment by jdavidbakr** [comment]
At this time I don't plan to maintain Lumen support.  From what I've read, Lumen is kind of dying if it's not already dead, and I've tried to have Lumen support in my packages only for that to cause issues I can't support (because I don't use Lumen).
