### ISSUE TITLE
Incoming Emails

### ISSUE THREAD

**Issue by alblez** [jdavidbakr/mail-tracker#96]
This package is quite convenient when I want to track outgoing emails, but I am looking for an approach to store incoming emails, I have implemented mail routing with Mailgun and I am considering using the Mailgun webhook to create new email records, but this It is also cumbersome, is there any way to do this with the package or extend a package class to create the records in the table sent_emails.
Thanks in advance for any help

**Comment by jdavidbakr** [comment]
No, consuming emails is outside of the scope of this package.
