### ISSUE TITLE
Is there a way to disallow tracking for certain links?

### ISSUE THREAD

**Issue by abishekrsrikaanth** [jdavidbakr/mail-tracker#97]
Is there a way to exclude certain links so they don't get tracked. My app has the unsubscribe links on them and they get captured on the link clicked table. Is there a good way to do it, if not, can this feature be added, something similar to how CSRF tokens are excluded from certain routes in laravel.  https://github.com/laravel/laravel/blob/master/app/Http/Middleware/VerifyCsrfToken.php#L21

**Comment by jdavidbakr** [comment]
I'm not opposed to it if someone wants to make a pull request, but probably won't add it myself.  I would think that it would be useful to know if an unsubscribe link was clicked in an email, but I can see if you also think that is unnecessary noise.  The way to do it with the current setup could be to add an observer to the SentEmailUrlClicked model to prevent it from getting saved based on your condition.
