### ISSUE TITLE
Why do we store the sender and the recipient in the format of "{name} <{address}>"?!

### ISSUE THREAD

**Issue by ScSherifTarek** [jdavidbakr/mail-tracker#99]
Is it for a specific purpose that we store the sender and the recipient in the format of "{name} <{address}>", I think it added a complication for querying the emails and using them without seeing any purpose for that!

**Comment by jdavidbakr** [comment]
It's doing that to match the RFC standards, although I would accept a pull request to create additional fields that separate it out into 4 additional attributes in the SentEmails model as long as the existing attributes are retained.

**Comment by louis-l** [comment]
Came across this, I think a better solution would be storing name and email separately (totally 4 columns) and then use model accessor to generate RFC format.

Example:

```php
public function getSenderInRFCFormatAttribute(): string 
{
    return sprintf('%s <%s>', $this->sender_name, $this->sender_email);
}
```

If dont like the duplicate data, can even remove the `sender` and `recipient` column and then use accessor to generate that programmatically.

**Comment by ScSherifTarek** [comment]
@louis-l 
Yes, that would be good but I can't see any part of the package code trying to access the sender or recipient if you saw one please mention it. but I think in general, having an `accessor` for the `sender` and `recipient` will reduce the change needed in the current package users code.

**Comment by jdavidbakr** [comment]
Updated in version 5.x
